/*
 jQuery JavaScript Library v3.4.1
 https://jquery.com/

 Includes Sizzle.js
 https://sizzlejs.com/

 Copyright JS Foundation and other contributors
 Released under the MIT license
 https://jquery.org/license

 Date: 2019-05-01T21:04Z
 Sizzle CSS Selector Engine v2.3.4
 https://sizzlejs.com/

 Copyright JS Foundation and other contributors
 Released under the MIT license
 https://js.foundation/

 Date: 2019-04-08
 Copyright (c) 2008 Yii Software LLC
 @license http://www.yiiframework.com/license/
 @author Qiang Xue <qiang.xue@gmail.com>
 @since 2.0
*/
var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.findInternal=function(m,I,O){m instanceof String&&(m=String(m));for(var H=m.length,R=0;R<H;R++){var M=m[R];if(I.call(O,M,R,m))return{i:R,v:M}}return{i:-1,v:void 0}};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.SIMPLE_FROUND_POLYFILL=!1;
$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(m,I,O){m!=Array.prototype&&m!=Object.prototype&&(m[I]=O.value)};$jscomp.getGlobal=function(m){return"undefined"!=typeof window&&window===m?m:"undefined"!=typeof global&&null!=global?global:m};$jscomp.global=$jscomp.getGlobal(this);
$jscomp.polyfill=function(m,I,O,H){if(I){O=$jscomp.global;m=m.split(".");for(H=0;H<m.length-1;H++){var R=m[H];R in O||(O[R]={});O=O[R]}m=m[m.length-1];H=O[m];I=I(H);I!=H&&null!=I&&$jscomp.defineProperty(O,m,{configurable:!0,writable:!0,value:I})}};$jscomp.polyfill("Array.prototype.find",function(m){return m?m:function(m,O){return $jscomp.findInternal(this,m,O).v}},"es6","es3");
(function(m,I){"object"===typeof module&&"object"===typeof module.exports?module.exports=m.document?I(m,!0):function(m){if(!m.document)throw Error("jQuery requires a window with a document");return I(m)}:I(m)})("undefined"!==typeof window?window:this,function(m,I){function O(a,b,c){c=c||x;var e,d=c.createElement("script");d.text=a;if(b)for(e in Pb)(a=b[e]||b.getAttribute&&b.getAttribute(e))&&d.setAttribute(e,a);c.head.appendChild(d).parentNode.removeChild(d)}function H(a){return null==a?a+"":"object"===
typeof a||"function"===typeof a?Ia[hb.call(a)]||"object":typeof a}function R(a){var b=!!a&&"length"in a&&a.length,c=H(a);return t(a)||va(a)?!1:"array"===c||0===b||"number"===typeof b&&0<b&&b-1 in a}function M(a,b){return a.nodeName&&a.nodeName.toLowerCase()===b.toLowerCase()}function aa(a,b,c){return t(b)?d.grep(a,function(a,d){return!!b.call(a,d,a)!==c}):b.nodeType?d.grep(a,function(a){return a===b!==c}):"string"!==typeof b?d.grep(a,function(a){return-1<Ja.call(b,a)!==c}):d.filter(b,a,c)}function y(a,
b){for(;(a=a[b])&&1!==a.nodeType;);return a}function p(a){var b={};d.each(a.match(ba)||[],function(a,e){b[e]=!0});return b}function q(a){return a}function r(a){throw a;}function K(a,b,c,e){var d;try{a&&t(d=a.promise)?d.call(a).done(b).fail(c):a&&t(d=a.then)?d.call(a,b,c):b.apply(void 0,[a].slice(e))}catch(g){c.apply(void 0,[g])}}function A(){x.removeEventListener("DOMContentLoaded",A);m.removeEventListener("load",A);d.ready()}function F(a,b){return b.toUpperCase()}function u(a){return a.replace(Qb,
"ms-").replace(Rb,F)}function V(){this.expando=d.expando+V.uid++}function Ba(a,b,c){if(void 0===c&&1===a.nodeType)if(c="data-"+b.replace(Sb,"-$&").toLowerCase(),c=a.getAttribute(c),"string"===typeof c){try{var e=c;c="true"===e?!0:"false"===e?!1:"null"===e?null:e===+e+""?+e:Tb.test(e)?JSON.parse(e):e}catch(f){}P.set(a,b,c)}else c=void 0;return c}function Ka(a,b,c,e){var f,g=20,h=e?function(){return e.cur()}:function(){return d.css(a,b,"")},k=h(),l=c&&c[3]||(d.cssNumber[b]?"":"px"),n=a.nodeType&&(d.cssNumber[b]||
"px"!==l&&+k)&&wa.exec(d.css(a,b));if(n&&n[3]!==l){k/=2;l=l||n[3];for(n=+k||1;g--;)d.style(a,b,n+l),0>=(1-f)*(1-(f=h()/k||.5))&&(g=0),n/=f;n*=2;d.style(a,b,n+l);c=c||[]}if(c){n=+n||+k||0;var m=c[1]?n+(c[1]+1)*c[2]:+c[2];e&&(e.unit=l,e.start=n,e.end=m)}return m}function xa(a,b){for(var c,e,f=[],g=0,h=a.length;g<h;g++)if(e=a[g],e.style)if(c=e.style.display,b){if("none"===c&&(f[g]=v.get(e,"display")||null,f[g]||(e.style.display="")),""===e.style.display&&Ma(e)){c=g;var k=e.ownerDocument;e=e.nodeName;
var l=ib[e];l||(k=k.body.appendChild(k.createElement(e)),l=d.css(k,"display"),k.parentNode.removeChild(k),"none"===l&&(l="block"),ib[e]=l);k=l;f[c]=k}}else"none"!==c&&(f[g]="none",v.set(e,"display",c));for(g=0;g<h;g++)null!=f[g]&&(a[g].style.display=f[g]);return a}function T(a,b){var c="undefined"!==typeof a.getElementsByTagName?a.getElementsByTagName(b||"*"):"undefined"!==typeof a.querySelectorAll?a.querySelectorAll(b||"*"):[];return void 0===b||b&&M(a,b)?d.merge([a],c):c}function Fa(a,b){for(var c=
0,e=a.length;c<e;c++)v.set(a[c],"globalEval",!b||v.get(b[c],"globalEval"))}function Na(a,b,c,e,f){for(var g,h,k,l=b.createDocumentFragment(),n=[],m=0,G=a.length;m<G;m++)if((g=a[m])||0===g)if("object"===H(g))d.merge(n,g.nodeType?[g]:g);else if(Ub.test(g)){h=h||l.appendChild(b.createElement("div"));k=(jb.exec(g)||["",""])[1].toLowerCase();k=S[k]||S._default;h.innerHTML=k[1]+d.htmlPrefilter(g)+k[2];for(k=k[0];k--;)h=h.lastChild;d.merge(n,h.childNodes);h=l.firstChild;h.textContent=""}else n.push(b.createTextNode(g));
l.textContent="";for(m=0;g=n[m++];)if(e&&-1<d.inArray(g,e))f&&f.push(g);else if(a=ca(g),h=T(l.appendChild(g),"script"),a&&Fa(h),c)for(k=0;g=h[k++];)kb.test(g.type||"")&&c.push(g);return l}function ya(){return!0}function ma(){return!1}function Vb(a,b){a:{try{var c=x.activeElement;break a}catch(e){}c=void 0}return a===c===("focus"===b)}function Ua(a,b,c,e,f,g){var h;if("object"===typeof b){"string"!==typeof c&&(e=e||c,c=void 0);for(h in b)Ua(a,h,c,e,b[h],g);return a}null==e&&null==f?(f=c,e=c=void 0):
null==f&&("string"===typeof c?(f=e,e=void 0):(f=e,e=c,c=void 0));if(!1===f)f=ma;else if(!f)return a;if(1===g){var k=f;f=function(a){d().off(a);return k.apply(this,arguments)};f.guid=k.guid||(k.guid=d.guid++)}return a.each(function(){d.event.add(this,b,f,e,c)})}function Oa(a,b,c){c?(v.set(a,b,!1),d.event.add(a,b,{namespace:!1,handler:function(a){var e=v.get(this,b);if(a.isTrigger&1&&this[b])if(e.length)(d.event.special[b]||{}).delegateType&&a.stopPropagation();else{e=ja.call(arguments);v.set(this,
b,e);var g=c(this,b);this[b]();var h=v.get(this,b);e!==h||g?v.set(this,b,!1):h={};if(e!==h)return a.stopImmediatePropagation(),a.preventDefault(),h.value}else e.length&&(v.set(this,b,{value:d.event.trigger(d.extend(e[0],d.Event.prototype),e.slice(1),this)}),a.stopImmediatePropagation())}})):void 0===v.get(a,b)&&d.event.add(a,b,ya)}function lb(a,b){return M(a,"table")&&M(11!==b.nodeType?b:b.firstChild,"tr")?d(a).children("tbody")[0]||a:a}function Wb(a){a.type=(null!==a.getAttribute("type"))+"/"+a.type;
return a}function Xb(a){"true/"===(a.type||"").slice(0,5)?a.type=a.type.slice(5):a.removeAttribute("type");return a}function mb(a,b){var c,e;if(1===b.nodeType){if(v.hasData(a)){var f=v.access(a);var g=v.set(b,f);if(f=f.events)for(e in delete g.handle,g.events={},f)for(g=0,c=f[e].length;g<c;g++)d.event.add(b,e,f[e][g])}P.hasData(a)&&(a=P.access(a),a=d.extend({},a),P.set(b,a))}}function za(a,b,c,e){b=nb.apply([],b);var f,g=0,h=a.length,k=h-1,l=b[0],n=t(l);if(n||1<h&&"string"===typeof l&&!z.checkClone&&
Yb.test(l))return a.each(function(d){var f=a.eq(d);n&&(b[0]=l.call(this,d,f.html()));za(f,b,c,e)});if(h){var m=Na(b,a[0].ownerDocument,!1,a,e);var G=m.firstChild;1===m.childNodes.length&&(m=G);if(G||e){G=d.map(T(m,"script"),Wb);for(f=G.length;g<h;g++){var p=m;g!==k&&(p=d.clone(p,!0,!0),f&&d.merge(G,T(p,"script")));c.call(a[g],p,g)}if(f)for(m=G[G.length-1].ownerDocument,d.map(G,Xb),g=0;g<f;g++)p=G[g],kb.test(p.type||"")&&!v.access(p,"globalEval")&&d.contains(m,p)&&(p.src&&"module"!==(p.type||"").toLowerCase()?
d._evalUrl&&!p.noModule&&d._evalUrl(p.src,{nonce:p.nonce||p.getAttribute("nonce")}):O(p.textContent.replace($b,""),p,m))}}return a}function ob(a,b,c){for(var e=b?d.filter(b,a):a,f=0;null!=(b=e[f]);f++)c||1!==b.nodeType||d.cleanData(T(b)),b.parentNode&&(c&&ca(b)&&Fa(T(b,"script")),b.parentNode.removeChild(b));return a}function Ca(a,b,c){var e=a.style;if(c=c||Pa(a)){var f=c.getPropertyValue(b)||c[b];""!==f||ca(a)||(f=d.style(a,b));if(!z.pixelBoxStyles()&&Va.test(f)&&ac.test(b)){a=e.width;b=e.minWidth;
var g=e.maxWidth;e.minWidth=e.maxWidth=e.width=f;f=c.width;e.width=a;e.minWidth=b;e.maxWidth=g}}return void 0!==f?f+"":f}function pb(a,b){return{get:function(){if(a())delete this.get;else return(this.get=b).apply(this,arguments)}}}function Wa(a){var b=d.cssProps[a]||qb[a];if(b)return b;if(a in rb)return a;a:{b=a;for(var c=b[0].toUpperCase()+b.slice(1),e=sb.length;e--;)if(b=sb[e]+c,b in rb)break a;b=void 0}return qb[a]=b||a}function tb(a,b,c){return(a=wa.exec(b))?Math.max(0,a[2]-(c||0))+(a[3]||"px"):
b}function Xa(a,b,c,e,f,g){var h="width"===b?1:0,k=0,l=0;if(c===(e?"border":"content"))return 0;for(;4>h;h+=2)"margin"===c&&(l+=d.css(a,c+Z[h],!0,f)),e?("content"===c&&(l-=d.css(a,"padding"+Z[h],!0,f)),"margin"!==c&&(l-=d.css(a,"border"+Z[h]+"Width",!0,f))):(l+=d.css(a,"padding"+Z[h],!0,f),"padding"!==c?l+=d.css(a,"border"+Z[h]+"Width",!0,f):k+=d.css(a,"border"+Z[h]+"Width",!0,f));!e&&0<=g&&(l+=Math.max(0,Math.ceil(a["offset"+b[0].toUpperCase()+b.slice(1)]-g-l-k-.5))||0);return l}function ub(a,b,
c){var e=Pa(a),f=(!z.boxSizingReliable()||c)&&"border-box"===d.css(a,"boxSizing",!1,e),g=f,h=Ca(a,b,e),k="offset"+b[0].toUpperCase()+b.slice(1);if(Va.test(h)){if(!c)return h;h="auto"}(!z.boxSizingReliable()&&f||"auto"===h||!parseFloat(h)&&"inline"===d.css(a,"display",!1,e))&&a.getClientRects().length&&(f="border-box"===d.css(a,"boxSizing",!1,e),(g=k in a)&&(h=a[k]));h=parseFloat(h)||0;return h+Xa(a,b,c||(f?"border":"content"),g,e,h)+"px"}function Y(a,b,c,e,d){return new Y.prototype.init(a,b,c,e,d)}
function Ya(){Qa&&(!1===x.hidden&&m.requestAnimationFrame?m.requestAnimationFrame(Ya):m.setTimeout(Ya,d.fx.interval),d.fx.tick())}function vb(){m.setTimeout(function(){ka=void 0});return ka=Date.now()}function Ra(a,b){var c=0,e={height:a};for(b=b?1:0;4>c;c+=2-b){var d=Z[c];e["margin"+d]=e["padding"+d]=a}b&&(e.opacity=e.width=a);return e}function wb(a,b,c){for(var e,d=(U.tweeners[b]||[]).concat(U.tweeners["*"]),g=0,h=d.length;g<h;g++)if(e=d[g].call(c,b,a))return e}function bc(a,b){var c,e;for(c in a){var f=
u(c);var g=b[f];var h=a[c];Array.isArray(h)&&(g=h[1],h=a[c]=h[0]);c!==f&&(a[f]=h,delete a[c]);if((e=d.cssHooks[f])&&"expand"in e)for(c in h=e.expand(h),delete a[f],h)c in a||(a[c]=h[c],b[c]=g);else b[f]=g}}function U(a,b,c){var e,f=0,g=U.prefilters.length,h=d.Deferred().always(function(){delete k.elem}),k=function(){if(e)return!1;var b=ka||vb();b=Math.max(0,l.startTime+l.duration-b);for(var c=1-(b/l.duration||0),d=0,f=l.tweens.length;d<f;d++)l.tweens[d].run(c);h.notifyWith(a,[l,c,b]);if(1>c&&f)return b;
f||h.notifyWith(a,[l,1,0]);h.resolveWith(a,[l]);return!1},l=h.promise({elem:a,props:d.extend({},b),opts:d.extend(!0,{specialEasing:{},easing:d.easing._default},c),originalProperties:b,originalOptions:c,startTime:ka||vb(),duration:c.duration,tweens:[],createTween:function(b,c){b=d.Tween(a,l.opts,b,c,l.opts.specialEasing[b]||l.opts.easing);l.tweens.push(b);return b},stop:function(b){var c=0,d=b?l.tweens.length:0;if(e)return this;for(e=!0;c<d;c++)l.tweens[c].run(1);b?(h.notifyWith(a,[l,1,0]),h.resolveWith(a,
[l,b])):h.rejectWith(a,[l,b]);return this}});c=l.props;for(bc(c,l.opts.specialEasing);f<g;f++)if(b=U.prefilters[f].call(l,a,c,l.opts))return t(b.stop)&&(d._queueHooks(l.elem,l.opts.queue).stop=b.stop.bind(b)),b;d.map(c,wb,l);t(l.opts.start)&&l.opts.start.call(a,l);l.progress(l.opts.progress).done(l.opts.done,l.opts.complete).fail(l.opts.fail).always(l.opts.always);d.fx.timer(d.extend(k,{elem:a,anim:l,queue:l.opts.queue}));return l}function na(a){return(a.match(ba)||[]).join(" ")}function da(a){return a.getAttribute&&
a.getAttribute("class")||""}function Za(a){return Array.isArray(a)?a:"string"===typeof a?a.match(ba)||[]:[]}function $a(a,b,c,e){var f;if(Array.isArray(b))d.each(b,function(b,d){c||cc.test(a)?e(a,d):$a(a+"["+("object"===typeof d&&null!=d?b:"")+"]",d,c,e)});else if(c||"object"!==H(b))e(a,b);else for(f in b)$a(a+"["+f+"]",b[f],c,e)}function xb(a){return function(b,c){"string"!==typeof b&&(c=b,b="*");var d=0,f=b.toLowerCase().match(ba)||[];if(t(c))for(;b=f[d++];)"+"===b[0]?(b=b.slice(1)||"*",(a[b]=a[b]||
[]).unshift(c)):(a[b]=a[b]||[]).push(c)}}function yb(a,b,c,e){function f(k){var l;g[k]=!0;d.each(a[k]||[],function(a,d){a=d(b,c,e);if("string"===typeof a&&!h&&!g[a])return b.dataTypes.unshift(a),f(a),!1;if(h)return!(l=a)});return l}var g={},h=a===ab;return f(b.dataTypes[0])||!g["*"]&&f("*")}function bb(a,b){var c,e,f=d.ajaxSettings.flatOptions||{};for(c in b)void 0!==b[c]&&((f[c]?a:e||(e={}))[c]=b[c]);e&&d.extend(!0,a,e);return a}var oa=[],x=m.document,dc=Object.getPrototypeOf,ja=oa.slice,nb=oa.concat,
cb=oa.push,Ja=oa.indexOf,Ia={},hb=Ia.toString,Sa=Ia.hasOwnProperty,zb=Sa.toString,ec=zb.call(Object),z={},t=function(a){return"function"===typeof a&&"number"!==typeof a.nodeType},va=function(a){return null!=a&&a===a.window},Pb={type:!0,src:!0,nonce:!0,noModule:!0},d=function(a,b){return new d.fn.init(a,b)},fc=/^[\s\uFEFF\xA0]+|[\s\uFEFF\xA0]+$/g;d.fn=d.prototype={jquery:"3.4.1",constructor:d,length:0,toArray:function(){return ja.call(this)},get:function(a){return null==a?ja.call(this):0>a?this[a+
this.length]:this[a]},pushStack:function(a){a=d.merge(this.constructor(),a);a.prevObject=this;return a},each:function(a){return d.each(this,a)},map:function(a){return this.pushStack(d.map(this,function(b,c){return a.call(b,c,b)}))},slice:function(){return this.pushStack(ja.apply(this,arguments))},first:function(){return this.eq(0)},last:function(){return this.eq(-1)},eq:function(a){var b=this.length;a=+a+(0>a?b:0);return this.pushStack(0<=a&&a<b?[this[a]]:[])},end:function(){return this.prevObject||
this.constructor()},push:cb,sort:oa.sort,splice:oa.splice};d.extend=d.fn.extend=function(){var a,b,c,e=arguments[0]||{},f=1,g=arguments.length,h=!1;"boolean"===typeof e&&(h=e,e=arguments[f]||{},f++);"object"===typeof e||t(e)||(e={});f===g&&(e=this,f--);for(;f<g;f++)if(null!=(a=arguments[f]))for(b in a){var k=a[b];if("__proto__"!==b&&e!==k)if(h&&k&&(d.isPlainObject(k)||(c=Array.isArray(k)))){var l=e[b];l=c&&!Array.isArray(l)?[]:c||d.isPlainObject(l)?l:{};c=!1;e[b]=d.extend(h,l,k)}else void 0!==k&&
(e[b]=k)}return e};d.extend({expando:"jQuery"+("3.4.1"+Math.random()).replace(/\D/g,""),isReady:!0,error:function(a){throw Error(a);},noop:function(){},isPlainObject:function(a){if(!a||"[object Object]"!==hb.call(a))return!1;a=dc(a);if(!a)return!0;a=Sa.call(a,"constructor")&&a.constructor;return"function"===typeof a&&zb.call(a)===ec},isEmptyObject:function(a){for(var b in a)return!1;return!0},globalEval:function(a,b){O(a,{nonce:b&&b.nonce})},each:function(a,b){var c,d=0;if(R(a))for(c=a.length;d<c&&
!1!==b.call(a[d],d,a[d]);d++);else for(d in a)if(!1===b.call(a[d],d,a[d]))break;return a},trim:function(a){return null==a?"":(a+"").replace(fc,"")},makeArray:function(a,b){b=b||[];null!=a&&(R(Object(a))?d.merge(b,"string"===typeof a?[a]:a):cb.call(b,a));return b},inArray:function(a,b,c){return null==b?-1:Ja.call(b,a,c)},merge:function(a,b){for(var c=+b.length,d=0,f=a.length;d<c;d++)a[f++]=b[d];a.length=f;return a},grep:function(a,b,c){for(var d=[],f=0,g=a.length,h=!c;f<g;f++)c=!b(a[f],f),c!==h&&d.push(a[f]);
return d},map:function(a,b,c){var d,f=0,g=[];if(R(a))for(d=a.length;f<d;f++){var h=b(a[f],f,c);null!=h&&g.push(h)}else for(f in a)h=b(a[f],f,c),null!=h&&g.push(h);return nb.apply([],g)},guid:1,support:z});"function"===typeof Symbol&&(d.fn[Symbol.iterator]=oa[Symbol.iterator]);d.each("Boolean Number String Function Array Date RegExp Object Error Symbol".split(" "),function(a,b){Ia["[object "+b+"]"]=b.toLowerCase()});var sa=function(a){function b(a,b,c,d){var e,f,g,D;var h=b&&b.ownerDocument;var w=
b?b.nodeType:9;c=c||[];if("string"!==typeof a||!a||1!==w&&9!==w&&11!==w)return c;if(!d&&((b?b.ownerDocument||b:ea)!==B&&Da(b),b=b||B,fa)){if(11!==w&&(D=za.exec(a)))if(e=D[1])if(9===w)if(f=b.getElementById(e)){if(f.id===e)return c.push(f),c}else return c;else{if(h&&(f=h.getElementById(e))&&I(b,f)&&f.id===e)return c.push(f),c}else{if(D[2])return S.apply(c,b.getElementsByTagName(a)),c;if((e=D[3])&&Q.getElementsByClassName&&b.getElementsByClassName)return S.apply(c,b.getElementsByClassName(e)),c}if(!(!Q.qsa||
Ba[a+" "]||X&&X.test(a)||1===w&&"object"===b.nodeName.toLowerCase())){e=a;h=b;if(1===w&&ja.test(a)){(g=b.getAttribute("id"))?g=g.replace(ta,wa):b.setAttribute("id",g=C);w=la(a);for(h=w.length;h--;)w[h]="#"+g+" "+r(w[h]);e=w.join(",");h=ka.test(a)&&p(b.parentNode)||b}try{return S.apply(c,h.querySelectorAll(e)),c}catch(Kc){Ba(a,!0)}finally{g===C&&b.removeAttribute("id")}}}return Ea(a.replace(Z,"$1"),b,c,d)}function c(){function a(c,d){b.push(c+" ")>J.cacheLength&&delete a[b.shift()];return a[c+" "]=
d}var b=[];return a}function d(a){a[C]=!0;return a}function f(a){var b=B.createElement("fieldset");try{return!!a(b)}catch(w){return!1}finally{b.parentNode&&b.parentNode.removeChild(b)}}function g(a,b){a=a.split("|");for(var c=a.length;c--;)J.attrHandle[a[c]]=b}function h(a,b){var c=b&&a,d=c&&1===a.nodeType&&1===b.nodeType&&a.sourceIndex-b.sourceIndex;if(d)return d;if(c)for(;c=c.nextSibling;)if(c===b)return-1;return a?1:-1}function k(a){return function(b){return"input"===b.nodeName.toLowerCase()&&
b.type===a}}function l(a){return function(b){var c=b.nodeName.toLowerCase();return("input"===c||"button"===c)&&b.type===a}}function n(a){return function(b){return"form"in b?b.parentNode&&!1===b.disabled?"label"in b?"label"in b.parentNode?b.parentNode.disabled===a:b.disabled===a:b.isDisabled===a||b.isDisabled!==!a&&Na(b)===a:b.disabled===a:"label"in b?b.disabled===a:!1}}function m(a){return d(function(b){b=+b;return d(function(c,d){for(var e,f=a([],c.length,b),g=f.length;g--;)c[e=f[g]]&&(c[e]=!(d[e]=
c[e]))})})}function p(a){return a&&"undefined"!==typeof a.getElementsByTagName&&a}function q(){}function r(a){for(var b=0,c=a.length,d="";b<c;b++)d+=a[b].value;return d}function v(a,b,c){var d=b.dir,e=b.next,f=e||d,g=c&&"parentNode"===f,h=O++;return b.first?function(b,c,e){for(;b=b[d];)if(1===b.nodeType||g)return a(b,c,e);return!1}:function(b,c,D){var w,l=[pa,h];if(D)for(;b=b[d];){if((1===b.nodeType||g)&&a(b,c,D))return!0}else for(;b=b[d];)if(1===b.nodeType||g){var k=b[C]||(b[C]={});k=k[b.uniqueID]||
(k[b.uniqueID]={});if(e&&e===b.nodeName.toLowerCase())b=b[d]||b;else{if((w=k[f])&&w[0]===pa&&w[1]===h)return l[2]=w[2];k[f]=l;if(l[2]=a(b,c,D))return!0}}return!1}}function t(a){return 1<a.length?function(b,c,d){for(var e=a.length;e--;)if(!a[e](b,c,d))return!1;return!0}:a[0]}function x(a,b,c,d,e){for(var f,g=[],h=0,D=a.length,w=null!=b;h<D;h++)if(f=a[h])if(!c||c(f,d,e))g.push(f),w&&b.push(h);return g}function z(a,c,e,f,g,h){f&&!f[C]&&(f=z(f));g&&!g[C]&&(g=z(g,h));return d(function(d,h,D,w){var l,k=
[],n=[],L=h.length,m;if(!(m=d)){m=c||"*";for(var N=D.nodeType?[D]:D,p=[],Ga=0,La=N.length;Ga<La;Ga++)b(m,N[Ga],p);m=p}m=!a||!d&&c?m:x(m,k,a,D,w);N=e?g||(d?a:L||f)?[]:h:m;e&&e(m,N,D,w);if(f){var G=x(N,n);f(G,[],D,w);for(D=G.length;D--;)if(l=G[D])N[n[D]]=!(m[n[D]]=l)}if(d){if(g||a){if(g){G=[];for(D=N.length;D--;)(l=N[D])&&G.push(m[D]=l);g(null,N=[],G,w)}for(D=N.length;D--;)(l=N[D])&&-1<(G=g?U(d,l):k[D])&&(d[G]=!(h[G]=l))}}else N=x(N===h?N.splice(L,N.length):N),g?g(null,h,N,w):S.apply(h,N)})}function E(a){var b,
c,d=a.length,e=J.relative[a[0].type];var f=e||J.relative[" "];for(var g=e?1:0,h=v(function(a){return a===b},f,!0),D=v(function(a){return-1<U(b,a)},f,!0),l=[function(a,c,d){a=!e&&(d||c!==W)||((b=c).nodeType?h(a,c,d):D(a,c,d));b=null;return a}];g<d;g++)if(f=J.relative[a[g].type])l=[v(t(l),f)];else{f=J.filter[a[g].type].apply(null,a[g].matches);if(f[C]){for(c=++g;c<d&&!J.relative[a[c].type];c++);return z(1<g&&t(l),1<g&&r(a.slice(0,g-1).concat({value:" "===a[g-2].type?"*":""})).replace(Z,"$1"),f,g<c&&
E(a.slice(g,c)),c<d&&E(a=a.slice(c)),c<d&&r(a))}l.push(f)}return t(l)}function K(a,c){var e=0<c.length,f=0<a.length,g=function(d,g,h,D,l){var w,k,n=0,L="0",m=d&&[],N=[],p=W,G=d||f&&J.find.TAG("*",l),La=pa+=null==p?1:Math.random()||.1,Ga=G.length;for(l&&(W=g===B||g||l);L!==Ga&&null!=(w=G[L]);L++){if(f&&w){var q=0;g||w.ownerDocument===B||(Da(w),h=!fa);for(;k=a[q++];)if(k(w,g||B,h)){D.push(w);break}l&&(pa=La)}e&&((w=!k&&w)&&n--,d&&m.push(w))}n+=L;if(e&&L!==n){for(q=0;k=c[q++];)k(m,N,g,h);if(d){if(0<
n)for(;L--;)m[L]||N[L]||(N[L]=Y.call(D));N=x(N)}S.apply(D,N);l&&!d&&0<N.length&&1<n+c.length&&b.uniqueSort(D)}l&&(pa=La,W=p);return m};return e?d(g):g}var F,W,u,A,B,ha,fa,X,y,V,I,C="sizzle"+1*new Date,ea=a.document,pa=0,O=0,H=c(),M=c(),T=c(),Ba=c(),R=function(a,b){a===b&&(A=!0);return 0},ya={}.hasOwnProperty,P=[],Y=P.pop,xa=P.push,S=P.push,ma=P.slice,U=function(a,b){for(var c=0,d=a.length;c<d;c++)if(a[c]===b)return c;return-1},ba=/[\x20\t\r\n\f]+/g,Z=/^[\x20\t\r\n\f]+|((?:^|[^\\])(?:\\.)*)[\x20\t\r\n\f]+$/g,
ia=/^[\x20\t\r\n\f]*,[\x20\t\r\n\f]*/,aa=/^[\x20\t\r\n\f]*([>+~]|[\x20\t\r\n\f])[\x20\t\r\n\f]*/,ja=/[\x20\t\r\n\f]|>/,Ka=/:((?:\\.|[\w-]|[^\x00-\xa0])+)(?:\((('((?:\\.|[^\\'])*)'|"((?:\\.|[^\\"])*)")|((?:\\.|[^\\()[\]]|\[[\x20\t\r\n\f]*((?:\\.|[\w-]|[^\x00-\xa0])+)(?:[\x20\t\r\n\f]*([*^$|!~]?=)[\x20\t\r\n\f]*(?:'((?:\\.|[^\\'])*)'|"((?:\\.|[^\\"])*)"|((?:\\.|[\w-]|[^\x00-\xa0])+))|)[\x20\t\r\n\f]*\])*)|.*)\)|)/,na=/^(?:\\.|[\w-]|[^\x00-\xa0])+$/,da={ID:/^#((?:\\.|[\w-]|[^\x00-\xa0])+)/,CLASS:/^\.((?:\\.|[\w-]|[^\x00-\xa0])+)/,
TAG:/^((?:\\.|[\w-]|[^\x00-\xa0])+|[*])/,ATTR:/^\[[\x20\t\r\n\f]*((?:\\.|[\w-]|[^\x00-\xa0])+)(?:[\x20\t\r\n\f]*([*^$|!~]?=)[\x20\t\r\n\f]*(?:'((?:\\.|[^\\'])*)'|"((?:\\.|[^\\"])*)"|((?:\\.|[\w-]|[^\x00-\xa0])+))|)[\x20\t\r\n\f]*\]/,PSEUDO:/^:((?:\\.|[\w-]|[^\x00-\xa0])+)(?:\((('((?:\\.|[^\\'])*)'|"((?:\\.|[^\\"])*)")|((?:\\.|[^\\()[\]]|\[[\x20\t\r\n\f]*((?:\\.|[\w-]|[^\x00-\xa0])+)(?:[\x20\t\r\n\f]*([*^$|!~]?=)[\x20\t\r\n\f]*(?:'((?:\\.|[^\\'])*)'|"((?:\\.|[^\\"])*)"|((?:\\.|[\w-]|[^\x00-\xa0])+))|)[\x20\t\r\n\f]*\])*)|.*)\)|)/,
CHILD:/^:(only|first|last|nth|nth-last)-(child|of-type)(?:\([\x20\t\r\n\f]*(even|odd|(([+-]|)(\d*)n|)[\x20\t\r\n\f]*(?:([+-]|)[\x20\t\r\n\f]*(\d+)|))[\x20\t\r\n\f]*\)|)/i,bool:/^(?:checked|selected|async|autofocus|autoplay|controls|defer|disabled|hidden|ismap|loop|multiple|open|readonly|required|scoped)$/i,needsContext:/^[\x20\t\r\n\f]*[>+~]|:(even|odd|eq|gt|lt|nth|first|last)(?:\([\x20\t\r\n\f]*((?:-\d)?\d*)[\x20\t\r\n\f]*\)|)(?=[^-]|$)/i},oa=/HTML$/i,sa=/^(?:input|select|textarea|button)$/i,va=
/^h\d$/i,ca=/^[^{]+\{\s*\[native \w/,za=/^(?:#([\w-]+)|(\w+)|\.([\w-]+))$/,ka=/[+~]/,qa=/\\([\da-f]{1,6}[\x20\t\r\n\f]?|([\x20\t\r\n\f])|.)/ig,ra=function(a,b,c){a="0x"+b-65536;return a!==a||c?b:0>a?String.fromCharCode(a+65536):String.fromCharCode(a>>10|55296,a&1023|56320)},ta=/([\0-\x1f\x7f]|^-?\d)|^-$|[^\0-\x1f\x7f-\uFFFF\w-]/g,wa=function(a,b){return b?"\x00"===a?"\ufffd":a.slice(0,-1)+"\\"+a.charCodeAt(a.length-1).toString(16)+" ":"\\"+a},Fa=function(){Da()},Na=v(function(a){return!0===a.disabled&&
"fieldset"===a.nodeName.toLowerCase()},{dir:"parentNode",next:"legend"});try{S.apply(P=ma.call(ea.childNodes),ea.childNodes),P[ea.childNodes.length].nodeType}catch(D){S={apply:P.length?function(a,b){xa.apply(a,ma.call(b))}:function(a,b){for(var c=a.length,d=0;a[c++]=b[d++];);a.length=c-1}}}var Q=b.support={};var Ca=b.isXML=function(a){var b=(a.ownerDocument||a).documentElement;return!oa.test(a.namespaceURI||b&&b.nodeName||"HTML")};var Da=b.setDocument=function(a){var b;a=a?a.ownerDocument||a:ea;if(a===
B||9!==a.nodeType||!a.documentElement)return B;B=a;ha=B.documentElement;fa=!Ca(B);ea!==B&&(b=B.defaultView)&&b.top!==b&&(b.addEventListener?b.addEventListener("unload",Fa,!1):b.attachEvent&&b.attachEvent("onunload",Fa));Q.attributes=f(function(a){a.className="i";return!a.getAttribute("className")});Q.getElementsByTagName=f(function(a){a.appendChild(B.createComment(""));return!a.getElementsByTagName("*").length});Q.getElementsByClassName=ca.test(B.getElementsByClassName);Q.getById=f(function(a){ha.appendChild(a).id=
C;return!B.getElementsByName||!B.getElementsByName(C).length});Q.getById?(J.filter.ID=function(a){var b=a.replace(qa,ra);return function(a){return a.getAttribute("id")===b}},J.find.ID=function(a,b){if("undefined"!==typeof b.getElementById&&fa)return(a=b.getElementById(a))?[a]:[]}):(J.filter.ID=function(a){var b=a.replace(qa,ra);return function(a){return(a="undefined"!==typeof a.getAttributeNode&&a.getAttributeNode("id"))&&a.value===b}},J.find.ID=function(a,b){if("undefined"!==typeof b.getElementById&&
fa){var c,d=b.getElementById(a);if(d){if((c=d.getAttributeNode("id"))&&c.value===a)return[d];var e=b.getElementsByName(a);for(b=0;d=e[b++];)if((c=d.getAttributeNode("id"))&&c.value===a)return[d]}return[]}});J.find.TAG=Q.getElementsByTagName?function(a,b){if("undefined"!==typeof b.getElementsByTagName)return b.getElementsByTagName(a);if(Q.qsa)return b.querySelectorAll(a)}:function(a,b){var c=[],d=0;b=b.getElementsByTagName(a);if("*"===a){for(;a=b[d++];)1===a.nodeType&&c.push(a);return c}return b};
J.find.CLASS=Q.getElementsByClassName&&function(a,b){if("undefined"!==typeof b.getElementsByClassName&&fa)return b.getElementsByClassName(a)};y=[];X=[];if(Q.qsa=ca.test(B.querySelectorAll))f(function(a){ha.appendChild(a).innerHTML="<a id='"+C+"'></a><select id='"+C+"-\r\\' msallowcapture=''><option selected=''></option></select>";a.querySelectorAll("[msallowcapture^='']").length&&X.push("[*^$]=[\\x20\\t\\r\\n\\f]*(?:''|\"\")");a.querySelectorAll("[selected]").length||X.push("\\[[\\x20\\t\\r\\n\\f]*(?:value|checked|selected|async|autofocus|autoplay|controls|defer|disabled|hidden|ismap|loop|multiple|open|readonly|required|scoped)");
a.querySelectorAll("[id~="+C+"-]").length||X.push("~=");a.querySelectorAll(":checked").length||X.push(":checked");a.querySelectorAll("a#"+C+"+*").length||X.push(".#.+[+~]")}),f(function(a){a.innerHTML="<a href='' disabled='disabled'></a><select disabled='disabled'><option/></select>";var b=B.createElement("input");b.setAttribute("type","hidden");a.appendChild(b).setAttribute("name","D");a.querySelectorAll("[name=d]").length&&X.push("name[\\x20\\t\\r\\n\\f]*[*^$|!~]?=");2!==a.querySelectorAll(":enabled").length&&
X.push(":enabled",":disabled");ha.appendChild(a).disabled=!0;2!==a.querySelectorAll(":disabled").length&&X.push(":enabled",":disabled");a.querySelectorAll("*,:x");X.push(",.*:")});(Q.matchesSelector=ca.test(V=ha.matches||ha.webkitMatchesSelector||ha.mozMatchesSelector||ha.oMatchesSelector||ha.msMatchesSelector))&&f(function(a){Q.disconnectedMatch=V.call(a,"*");V.call(a,"[s!='']:x");y.push("!=",":((?:\\\\.|[\\w-]|[^\x00-\\xa0])+)(?:\\((('((?:\\\\.|[^\\\\'])*)'|\"((?:\\\\.|[^\\\\\"])*)\")|((?:\\\\.|[^\\\\()[\\]]|\\[[\\x20\\t\\r\\n\\f]*((?:\\\\.|[\\w-]|[^\x00-\\xa0])+)(?:[\\x20\\t\\r\\n\\f]*([*^$|!~]?=)[\\x20\\t\\r\\n\\f]*(?:'((?:\\\\.|[^\\\\'])*)'|\"((?:\\\\.|[^\\\\\"])*)\"|((?:\\\\.|[\\w-]|[^\x00-\\xa0])+))|)[\\x20\\t\\r\\n\\f]*\\])*)|.*)\\)|)")});
X=X.length&&new RegExp(X.join("|"));y=y.length&&new RegExp(y.join("|"));I=(b=ca.test(ha.compareDocumentPosition))||ca.test(ha.contains)?function(a,b){var c=9===a.nodeType?a.documentElement:a;b=b&&b.parentNode;return a===b||!!(b&&1===b.nodeType&&(c.contains?c.contains(b):a.compareDocumentPosition&&a.compareDocumentPosition(b)&16))}:function(a,b){if(b)for(;b=b.parentNode;)if(b===a)return!0;return!1};R=b?function(a,b){if(a===b)return A=!0,0;var c=!a.compareDocumentPosition-!b.compareDocumentPosition;
if(c)return c;c=(a.ownerDocument||a)===(b.ownerDocument||b)?a.compareDocumentPosition(b):1;return c&1||!Q.sortDetached&&b.compareDocumentPosition(a)===c?a===B||a.ownerDocument===ea&&I(ea,a)?-1:b===B||b.ownerDocument===ea&&I(ea,b)?1:u?U(u,a)-U(u,b):0:c&4?-1:1}:function(a,b){if(a===b)return A=!0,0;var c=0,d=a.parentNode,e=b.parentNode,f=[a],g=[b];if(!d||!e)return a===B?-1:b===B?1:d?-1:e?1:u?U(u,a)-U(u,b):0;if(d===e)return h(a,b);for(;a=a.parentNode;)f.unshift(a);for(a=b;a=a.parentNode;)g.unshift(a);
for(;f[c]===g[c];)c++;return c?h(f[c],g[c]):f[c]===ea?-1:g[c]===ea?1:0};return B};b.matches=function(a,c){return b(a,null,null,c)};b.matchesSelector=function(a,c){(a.ownerDocument||a)!==B&&Da(a);if(!(!Q.matchesSelector||!fa||Ba[c+" "]||y&&y.test(c)||X&&X.test(c)))try{var d=V.call(a,c);if(d||Q.disconnectedMatch||a.document&&11!==a.document.nodeType)return d}catch(N){Ba(c,!0)}return 0<b(c,B,null,[a]).length};b.contains=function(a,b){(a.ownerDocument||a)!==B&&Da(a);return I(a,b)};b.attr=function(a,b){(a.ownerDocument||
a)!==B&&Da(a);var c=J.attrHandle[b.toLowerCase()];c=c&&ya.call(J.attrHandle,b.toLowerCase())?c(a,b,!fa):void 0;return void 0!==c?c:Q.attributes||!fa?a.getAttribute(b):(c=a.getAttributeNode(b))&&c.specified?c.value:null};b.escape=function(a){return(a+"").replace(ta,wa)};b.error=function(a){throw Error("Syntax error, unrecognized expression: "+a);};b.uniqueSort=function(a){var b,c=[],d=0,e=0;A=!Q.detectDuplicates;u=!Q.sortStable&&a.slice(0);a.sort(R);if(A){for(;b=a[e++];)b===a[e]&&(d=c.push(e));for(;d--;)a.splice(c[d],
1)}u=null;return a};var ua=b.getText=function(a){var b="",c=0;var d=a.nodeType;if(!d)for(;d=a[c++];)b+=ua(d);else if(1===d||9===d||11===d){if("string"===typeof a.textContent)return a.textContent;for(a=a.firstChild;a;a=a.nextSibling)b+=ua(a)}else if(3===d||4===d)return a.nodeValue;return b};var J=b.selectors={cacheLength:50,createPseudo:d,match:da,attrHandle:{},find:{},relative:{">":{dir:"parentNode",first:!0}," ":{dir:"parentNode"},"+":{dir:"previousSibling",first:!0},"~":{dir:"previousSibling"}},
preFilter:{ATTR:function(a){a[1]=a[1].replace(qa,ra);a[3]=(a[3]||a[4]||a[5]||"").replace(qa,ra);"~="===a[2]&&(a[3]=" "+a[3]+" ");return a.slice(0,4)},CHILD:function(a){a[1]=a[1].toLowerCase();"nth"===a[1].slice(0,3)?(a[3]||b.error(a[0]),a[4]=+(a[4]?a[5]+(a[6]||1):2*("even"===a[3]||"odd"===a[3])),a[5]=+(a[7]+a[8]||"odd"===a[3])):a[3]&&b.error(a[0]);return a},PSEUDO:function(a){var b,c=!a[6]&&a[2];if(da.CHILD.test(a[0]))return null;a[3]?a[2]=a[4]||a[5]||"":c&&Ka.test(c)&&(b=la(c,!0))&&(b=c.indexOf(")",
c.length-b)-c.length)&&(a[0]=a[0].slice(0,b),a[2]=c.slice(0,b));return a.slice(0,3)}},filter:{TAG:function(a){var b=a.replace(qa,ra).toLowerCase();return"*"===a?function(){return!0}:function(a){return a.nodeName&&a.nodeName.toLowerCase()===b}},CLASS:function(a){var b=H[a+" "];return b||(b=new RegExp("(^|[\\x20\\t\\r\\n\\f])"+a+"([\\x20\\t\\r\\n\\f]|$)"),H(a,function(a){return b.test("string"===typeof a.className&&a.className||"undefined"!==typeof a.getAttribute&&a.getAttribute("class")||"")}))},ATTR:function(a,
c,d){return function(e){e=b.attr(e,a);if(null==e)return"!="===c;if(!c)return!0;e+="";return"="===c?e===d:"!="===c?e!==d:"^="===c?d&&0===e.indexOf(d):"*="===c?d&&-1<e.indexOf(d):"$="===c?d&&e.slice(-d.length)===d:"~="===c?-1<(" "+e.replace(ba," ")+" ").indexOf(d):"|="===c?e===d||e.slice(0,d.length+1)===d+"-":!1}},CHILD:function(a,b,c,d,e){var f="nth"!==a.slice(0,3),g="last"!==a.slice(-4),h="of-type"===b;return 1===d&&0===e?function(a){return!!a.parentNode}:function(b,c,l){var k,n;c=f!==g?"nextSibling":
"previousSibling";var m=b.parentNode,D=h&&b.nodeName.toLowerCase();l=!l&&!h;var w=!1;if(m){if(f){for(;c;){for(k=b;k=k[c];)if(h?k.nodeName.toLowerCase()===D:1===k.nodeType)return!1;var p=c="only"===a&&!p&&"nextSibling"}return!0}p=[g?m.firstChild:m.lastChild];if(g&&l){k=m;var L=k[C]||(k[C]={});L=L[k.uniqueID]||(L[k.uniqueID]={});w=L[a]||[];w=(n=w[0]===pa&&w[1])&&w[2];for(k=n&&m.childNodes[n];k=++n&&k&&k[c]||(w=n=0)||p.pop();)if(1===k.nodeType&&++w&&k===b){L[a]=[pa,n,w];break}}else if(l&&(k=b,L=k[C]||
(k[C]={}),L=L[k.uniqueID]||(L[k.uniqueID]={}),w=L[a]||[],w=n=w[0]===pa&&w[1]),!1===w)for(;(k=++n&&k&&k[c]||(w=n=0)||p.pop())&&((h?k.nodeName.toLowerCase()!==D:1!==k.nodeType)||!++w||(l&&(L=k[C]||(k[C]={}),L=L[k.uniqueID]||(L[k.uniqueID]={}),L[a]=[pa,w]),k!==b)););w-=e;return w===d||0===w%d&&0<=w/d}}},PSEUDO:function(a,c){var e=J.pseudos[a]||J.setFilters[a.toLowerCase()]||b.error("unsupported pseudo: "+a);if(e[C])return e(c);if(1<e.length){var f=[a,a,"",c];return J.setFilters.hasOwnProperty(a.toLowerCase())?
d(function(a,b){for(var d,f=e(a,c),g=f.length;g--;)d=U(a,f[g]),a[d]=!(b[d]=f[g])}):function(a){return e(a,0,f)}}return e}},pseudos:{not:d(function(a){var b=[],c=[],e=Aa(a.replace(Z,"$1"));return e[C]?d(function(a,b,c,d){d=e(a,null,d,[]);for(var f=a.length;f--;)if(c=d[f])a[f]=!(b[f]=c)}):function(a,d,f){b[0]=a;e(b,null,f,c);b[0]=null;return!c.pop()}}),has:d(function(a){return function(c){return 0<b(a,c).length}}),contains:d(function(a){a=a.replace(qa,ra);return function(b){return-1<(b.textContent||
ua(b)).indexOf(a)}}),lang:d(function(a){na.test(a||"")||b.error("unsupported lang: "+a);a=a.replace(qa,ra).toLowerCase();return function(b){var c;do if(c=fa?b.lang:b.getAttribute("xml:lang")||b.getAttribute("lang"))return c=c.toLowerCase(),c===a||0===c.indexOf(a+"-");while((b=b.parentNode)&&1===b.nodeType);return!1}}),target:function(b){var c=a.location&&a.location.hash;return c&&c.slice(1)===b.id},root:function(a){return a===ha},focus:function(a){return a===B.activeElement&&(!B.hasFocus||B.hasFocus())&&
!!(a.type||a.href||~a.tabIndex)},enabled:n(!1),disabled:n(!0),checked:function(a){var b=a.nodeName.toLowerCase();return"input"===b&&!!a.checked||"option"===b&&!!a.selected},selected:function(a){a.parentNode&&a.parentNode.selectedIndex;return!0===a.selected},empty:function(a){for(a=a.firstChild;a;a=a.nextSibling)if(6>a.nodeType)return!1;return!0},parent:function(a){return!J.pseudos.empty(a)},header:function(a){return va.test(a.nodeName)},input:function(a){return sa.test(a.nodeName)},button:function(a){var b=
a.nodeName.toLowerCase();return"input"===b&&"button"===a.type||"button"===b},text:function(a){var b;return"input"===a.nodeName.toLowerCase()&&"text"===a.type&&(null==(b=a.getAttribute("type"))||"text"===b.toLowerCase())},first:m(function(){return[0]}),last:m(function(a,b){return[b-1]}),eq:m(function(a,b,c){return[0>c?c+b:c]}),even:m(function(a,b){for(var c=0;c<b;c+=2)a.push(c);return a}),odd:m(function(a,b){for(var c=1;c<b;c+=2)a.push(c);return a}),lt:m(function(a,b,c){for(b=0>c?c+b:c>b?b:c;0<=--b;)a.push(b);
return a}),gt:m(function(a,b,c){for(c=0>c?c+b:c;++c<b;)a.push(c);return a})}};J.pseudos.nth=J.pseudos.eq;for(F in{radio:!0,checkbox:!0,file:!0,password:!0,image:!0})J.pseudos[F]=k(F);for(F in{submit:!0,reset:!0})J.pseudos[F]=l(F);q.prototype=J.filters=J.pseudos;J.setFilters=new q;var la=b.tokenize=function(a,c){var d,e,f,g,h;if(g=M[a+" "])return c?0:g.slice(0);g=a;var k=[];for(h=J.preFilter;g;){if(!l||(d=ia.exec(g)))d&&(g=g.slice(d[0].length)||g),k.push(e=[]);var l=!1;if(d=aa.exec(g))l=d.shift(),
e.push({value:l,type:d[0].replace(Z," ")}),g=g.slice(l.length);for(f in J.filter)!(d=da[f].exec(g))||h[f]&&!(d=h[f](d))||(l=d.shift(),e.push({value:l,type:f,matches:d}),g=g.slice(l.length));if(!l)break}return c?g.length:g?b.error(a):M(a,k).slice(0)};var Aa=b.compile=function(a,b){var c,d=[],e=[],f=T[a+" "];if(!f){b||(b=la(a));for(c=b.length;c--;)f=E(b[c]),f[C]?d.push(f):e.push(f);f=T(a,K(e,d));f.selector=a}return f};var Ea=b.select=function(a,b,c,d){var e,f,g,h="function"===typeof a&&a,k=!d&&la(a=
h.selector||a);c=c||[];if(1===k.length){var l=k[0]=k[0].slice(0);if(2<l.length&&"ID"===(f=l[0]).type&&9===b.nodeType&&fa&&J.relative[l[1].type]){b=(J.find.ID(f.matches[0].replace(qa,ra),b)||[])[0];if(!b)return c;h&&(b=b.parentNode);a=a.slice(l.shift().value.length)}for(e=da.needsContext.test(a)?0:l.length;e--;){f=l[e];if(J.relative[g=f.type])break;if(g=J.find[g])if(d=g(f.matches[0].replace(qa,ra),ka.test(l[0].type)&&p(b.parentNode)||b)){l.splice(e,1);a=d.length&&r(l);if(!a)return S.apply(c,d),c;break}}}(h||
Aa(a,k))(d,b,!fa,c,!b||ka.test(a)&&p(b.parentNode)||b);return c};Q.sortStable=C.split("").sort(R).join("")===C;Q.detectDuplicates=!!A;Da();Q.sortDetached=f(function(a){return a.compareDocumentPosition(B.createElement("fieldset"))&1});f(function(a){a.innerHTML="<a href='#'></a>";return"#"===a.firstChild.getAttribute("href")})||g("type|href|height|width",function(a,b,c){if(!c)return a.getAttribute(b,"type"===b.toLowerCase()?1:2)});Q.attributes&&f(function(a){a.innerHTML="<input/>";a.firstChild.setAttribute("value",
"");return""===a.firstChild.getAttribute("value")})||g("value",function(a,b,c){if(!c&&"input"===a.nodeName.toLowerCase())return a.defaultValue});f(function(a){return null==a.getAttribute("disabled")})||g("checked|selected|async|autofocus|autoplay|controls|defer|disabled|hidden|ismap|loop|multiple|open|readonly|required|scoped",function(a,b,c){var d;if(!c)return!0===a[b]?b.toLowerCase():(d=a.getAttributeNode(b))&&d.specified?d.value:null});return b}(m);d.find=sa;d.expr=sa.selectors;d.expr[":"]=d.expr.pseudos;
d.uniqueSort=d.unique=sa.uniqueSort;d.text=sa.getText;d.isXMLDoc=sa.isXML;d.contains=sa.contains;d.escapeSelector=sa.escape;var ta=function(a,b,c){for(var e=[],f=void 0!==c;(a=a[b])&&9!==a.nodeType;)if(1===a.nodeType){if(f&&d(a).is(c))break;e.push(a)}return e},Ab=function(a,b){for(var c=[];a;a=a.nextSibling)1===a.nodeType&&a!==b&&c.push(a);return c},Bb=d.expr.match.needsContext,Cb=/^<([a-z][^\/\0>:\x20\t\r\n\f]*)[\x20\t\r\n\f]*\/?>(?:<\/\1>|)$/i;d.filter=function(a,b,c){var e=b[0];c&&(a=":not("+a+
")");return 1===b.length&&1===e.nodeType?d.find.matchesSelector(e,a)?[e]:[]:d.find.matches(a,d.grep(b,function(a){return 1===a.nodeType}))};d.fn.extend({find:function(a){var b,c=this.length,e=this;if("string"!==typeof a)return this.pushStack(d(a).filter(function(){for(b=0;b<c;b++)if(d.contains(e[b],this))return!0}));var f=this.pushStack([]);for(b=0;b<c;b++)d.find(a,e[b],f);return 1<c?d.uniqueSort(f):f},filter:function(a){return this.pushStack(aa(this,a||[],!1))},not:function(a){return this.pushStack(aa(this,
a||[],!0))},is:function(a){return!!aa(this,"string"===typeof a&&Bb.test(a)?d(a):a||[],!1).length}});var hc=/^(?:\s*(<[\w\W]+>)[^>]*|#([\w-]+))$/;(d.fn.init=function(a,b,c){if(!a)return this;c=c||ic;if("string"===typeof a){var e="<"===a[0]&&">"===a[a.length-1]&&3<=a.length?[null,a,null]:hc.exec(a);if(!e||!e[1]&&b)return!b||b.jquery?(b||c).find(a):this.constructor(b).find(a);if(e[1]){if(b=b instanceof d?b[0]:b,d.merge(this,d.parseHTML(e[1],b&&b.nodeType?b.ownerDocument||b:x,!0)),Cb.test(e[1])&&d.isPlainObject(b))for(e in b)if(t(this[e]))this[e](b[e]);
else this.attr(e,b[e])}else if(a=x.getElementById(e[2]))this[0]=a,this.length=1;return this}return a.nodeType?(this[0]=a,this.length=1,this):t(a)?void 0!==c.ready?c.ready(a):a(d):d.makeArray(a,this)}).prototype=d.fn;var ic=d(x);var jc=/^(?:parents|prev(?:Until|All))/,kc={children:!0,contents:!0,next:!0,prev:!0};d.fn.extend({has:function(a){var b=d(a,this),c=b.length;return this.filter(function(){for(var a=0;a<c;a++)if(d.contains(this,b[a]))return!0})},closest:function(a,b){var c,e=0,f=this.length,
g=[],h="string"!==typeof a&&d(a);if(!Bb.test(a))for(;e<f;e++)for(c=this[e];c&&c!==b;c=c.parentNode)if(11>c.nodeType&&(h?-1<h.index(c):1===c.nodeType&&d.find.matchesSelector(c,a))){g.push(c);break}return this.pushStack(1<g.length?d.uniqueSort(g):g)},index:function(a){return a?"string"===typeof a?Ja.call(d(a),this[0]):Ja.call(this,a.jquery?a[0]:a):this[0]&&this[0].parentNode?this.first().prevAll().length:-1},add:function(a,b){return this.pushStack(d.uniqueSort(d.merge(this.get(),d(a,b))))},addBack:function(a){return this.add(null==
a?this.prevObject:this.prevObject.filter(a))}});d.each({parent:function(a){return(a=a.parentNode)&&11!==a.nodeType?a:null},parents:function(a){return ta(a,"parentNode")},parentsUntil:function(a,b,c){return ta(a,"parentNode",c)},next:function(a){return y(a,"nextSibling")},prev:function(a){return y(a,"previousSibling")},nextAll:function(a){return ta(a,"nextSibling")},prevAll:function(a){return ta(a,"previousSibling")},nextUntil:function(a,b,c){return ta(a,"nextSibling",c)},prevUntil:function(a,b,c){return ta(a,
"previousSibling",c)},siblings:function(a){return Ab((a.parentNode||{}).firstChild,a)},children:function(a){return Ab(a.firstChild)},contents:function(a){if("undefined"!==typeof a.contentDocument)return a.contentDocument;M(a,"template")&&(a=a.content||a);return d.merge([],a.childNodes)}},function(a,b){d.fn[a]=function(c,e){var f=d.map(this,b,c);"Until"!==a.slice(-5)&&(e=c);e&&"string"===typeof e&&(f=d.filter(e,f));1<this.length&&(kc[a]||d.uniqueSort(f),jc.test(a)&&f.reverse());return this.pushStack(f)}});
var ba=/[^\x20\t\r\n\f]+/g;d.Callbacks=function(a){a="string"===typeof a?p(a):d.extend({},a);var b,c,e,f,g=[],h=[],k=-1,l=function(){f=f||a.once;for(e=b=!0;h.length;k=-1)for(c=h.shift();++k<g.length;)!1===g[k].apply(c[0],c[1])&&a.stopOnFalse&&(k=g.length,c=!1);a.memory||(c=!1);b=!1;f&&(g=c?[]:"")},n={add:function(){g&&(c&&!b&&(k=g.length-1,h.push(c)),function Zb(b){d.each(b,function(b,c){t(c)?a.unique&&n.has(c)||g.push(c):c&&c.length&&"string"!==H(c)&&Zb(c)})}(arguments),c&&!b&&l());return this},
remove:function(){d.each(arguments,function(a,b){for(var c;-1<(c=d.inArray(b,g,c));)g.splice(c,1),c<=k&&k--});return this},has:function(a){return a?-1<d.inArray(a,g):0<g.length},empty:function(){g&&(g=[]);return this},disable:function(){f=h=[];g=c="";return this},disabled:function(){return!g},lock:function(){f=h=[];c||b||(g=c="");return this},locked:function(){return!!f},fireWith:function(a,c){f||(c=c||[],c=[a,c.slice?c.slice():c],h.push(c),b||l());return this},fire:function(){n.fireWith(this,arguments);
return this},fired:function(){return!!e}};return n};d.extend({Deferred:function(a){var b=[["notify","progress",d.Callbacks("memory"),d.Callbacks("memory"),2],["resolve","done",d.Callbacks("once memory"),d.Callbacks("once memory"),0,"resolved"],["reject","fail",d.Callbacks("once memory"),d.Callbacks("once memory"),1,"rejected"]],c="pending",e={state:function(){return c},always:function(){f.done(arguments).fail(arguments);return this},"catch":function(a){return e.then(null,a)},pipe:function(){var a=
arguments;return d.Deferred(function(c){d.each(b,function(b,d){var e=t(a[d[4]])&&a[d[4]];f[d[1]](function(){var a=e&&e.apply(this,arguments);if(a&&t(a.promise))a.promise().progress(c.notify).done(c.resolve).fail(c.reject);else c[d[0]+"With"](this,e?[a]:arguments)})});a=null}).promise()},then:function(a,c,e){function f(a,b,c,e){return function(){var h=this,k=arguments,l=function(){if(!(a<g)){var d=c.apply(h,k);if(d===b.promise())throw new TypeError("Thenable self-resolution");var l=d&&("object"===
typeof d||"function"===typeof d)&&d.then;t(l)?e?l.call(d,f(g,b,q,e),f(g,b,r,e)):(g++,l.call(d,f(g,b,q,e),f(g,b,r,e),f(g,b,q,b.notifyWith))):(c!==q&&(h=void 0,k=[d]),(e||b.resolveWith)(h,k))}},n=e?l:function(){try{l()}catch(E){d.Deferred.exceptionHook&&d.Deferred.exceptionHook(E,n.stackTrace),a+1>=g&&(c!==r&&(h=void 0,k=[E]),b.rejectWith(h,k))}};a?n():(d.Deferred.getStackHook&&(n.stackTrace=d.Deferred.getStackHook()),m.setTimeout(n))}}var g=0;return d.Deferred(function(d){b[0][3].add(f(0,d,t(e)?e:
q,d.notifyWith));b[1][3].add(f(0,d,t(a)?a:q));b[2][3].add(f(0,d,t(c)?c:r))}).promise()},promise:function(a){return null!=a?d.extend(a,e):e}},f={};d.each(b,function(a,d){var g=d[2],h=d[5];e[d[1]]=g.add;h&&g.add(function(){c=h},b[3-a][2].disable,b[3-a][3].disable,b[0][2].lock,b[0][3].lock);g.add(d[3].fire);f[d[0]]=function(){f[d[0]+"With"](this===f?void 0:this,arguments);return this};f[d[0]+"With"]=g.fireWith});e.promise(f);a&&a.call(f,f);return f},when:function(a){var b=arguments.length,c=b,e=Array(c),
f=ja.call(arguments),g=d.Deferred(),h=function(a){return function(c){e[a]=this;f[a]=1<arguments.length?ja.call(arguments):c;--b||g.resolveWith(e,f)}};if(1>=b&&(K(a,g.done(h(c)).resolve,g.reject,!b),"pending"===g.state()||t(f[c]&&f[c].then)))return g.then();for(;c--;)K(f[c],h(c),g.reject);return g.promise()}});var lc=/^(Eval|Internal|Range|Reference|Syntax|Type|URI)Error$/;d.Deferred.exceptionHook=function(a,b){m.console&&m.console.warn&&a&&lc.test(a.name)&&m.console.warn("jQuery.Deferred exception: "+
a.message,a.stack,b)};d.readyException=function(a){m.setTimeout(function(){throw a;})};var db=d.Deferred();d.fn.ready=function(a){db.then(a).catch(function(a){d.readyException(a)});return this};d.extend({isReady:!1,readyWait:1,ready:function(a){(!0===a?--d.readyWait:d.isReady)||(d.isReady=!0,!0!==a&&0<--d.readyWait||db.resolveWith(x,[d]))}});d.ready.then=db.then;"complete"===x.readyState||"loading"!==x.readyState&&!x.documentElement.doScroll?m.setTimeout(d.ready):(x.addEventListener("DOMContentLoaded",
A),m.addEventListener("load",A));var ia=function(a,b,c,e,f,g,h){var k=0,l=a.length,n=null==c;if("object"===H(c))for(k in f=!0,c)ia(a,b,k,c[k],!0,g,h);else if(void 0!==e&&(f=!0,t(e)||(h=!0),n&&(h?(b.call(a,e),b=null):(n=b,b=function(a,b,c){return n.call(d(a),c)})),b))for(;k<l;k++)b(a[k],c,h?e:e.call(a[k],k,b(a[k],c)));return f?a:n?b.call(a):l?b(a[0],c):g},Qb=/^-ms-/,Rb=/-([a-z])/g,Ta=function(a){return 1===a.nodeType||9===a.nodeType||!+a.nodeType};V.uid=1;V.prototype={cache:function(a){var b=a[this.expando];
b||(b={},Ta(a)&&(a.nodeType?a[this.expando]=b:Object.defineProperty(a,this.expando,{value:b,configurable:!0})));return b},set:function(a,b,c){var d;a=this.cache(a);if("string"===typeof b)a[u(b)]=c;else for(d in b)a[u(d)]=b[d];return a},get:function(a,b){return void 0===b?this.cache(a):a[this.expando]&&a[this.expando][u(b)]},access:function(a,b,c){if(void 0===b||b&&"string"===typeof b&&void 0===c)return this.get(a,b);this.set(a,b,c);return void 0!==c?c:b},remove:function(a,b){var c,e=a[this.expando];
if(void 0!==e){if(void 0!==b)for(Array.isArray(b)?b=b.map(u):(b=u(b),b=b in e?[b]:b.match(ba)||[]),c=b.length;c--;)delete e[b[c]];if(void 0===b||d.isEmptyObject(e))a.nodeType?a[this.expando]=void 0:delete a[this.expando]}},hasData:function(a){a=a[this.expando];return void 0!==a&&!d.isEmptyObject(a)}};var v=new V,P=new V,Tb=/^(?:\{[\w\W]*\}|\[[\w\W]*\])$/,Sb=/[A-Z]/g;d.extend({hasData:function(a){return P.hasData(a)||v.hasData(a)},data:function(a,b,c){return P.access(a,b,c)},removeData:function(a,
b){P.remove(a,b)},_data:function(a,b,c){return v.access(a,b,c)},_removeData:function(a,b){v.remove(a,b)}});d.fn.extend({data:function(a,b){var c,d=this[0],f=d&&d.attributes;if(void 0===a){if(this.length){var g=P.get(d);if(1===d.nodeType&&!v.get(d,"hasDataAttrs")){for(c=f.length;c--;)if(f[c]){var h=f[c].name;0===h.indexOf("data-")&&(h=u(h.slice(5)),Ba(d,h,g[h]))}v.set(d,"hasDataAttrs",!0)}}return g}return"object"===typeof a?this.each(function(){P.set(this,a)}):ia(this,function(b){if(d&&void 0===b){var c=
P.get(d,a);if(void 0!==c)return c;c=Ba(d,a);if(void 0!==c)return c}else this.each(function(){P.set(this,a,b)})},null,b,1<arguments.length,null,!0)},removeData:function(a){return this.each(function(){P.remove(this,a)})}});d.extend({queue:function(a,b,c){if(a){b=(b||"fx")+"queue";var e=v.get(a,b);c&&(!e||Array.isArray(c)?e=v.access(a,b,d.makeArray(c)):e.push(c));return e||[]}},dequeue:function(a,b){b=b||"fx";var c=d.queue(a,b),e=c.length,f=c.shift(),g=d._queueHooks(a,b),h=function(){d.dequeue(a,b)};
"inprogress"===f&&(f=c.shift(),e--);f&&("fx"===b&&c.unshift("inprogress"),delete g.stop,f.call(a,h,g));!e&&g&&g.empty.fire()},_queueHooks:function(a,b){var c=b+"queueHooks";return v.get(a,c)||v.access(a,c,{empty:d.Callbacks("once memory").add(function(){v.remove(a,[b+"queue",c])})})}});d.fn.extend({queue:function(a,b){var c=2;"string"!==typeof a&&(b=a,a="fx",c--);return arguments.length<c?d.queue(this[0],a):void 0===b?this:this.each(function(){var c=d.queue(this,a,b);d._queueHooks(this,a);"fx"===
a&&"inprogress"!==c[0]&&d.dequeue(this,a)})},dequeue:function(a){return this.each(function(){d.dequeue(this,a)})},clearQueue:function(a){return this.queue(a||"fx",[])},promise:function(a,b){var c,e=1,f=d.Deferred(),g=this,h=this.length,k=function(){--e||f.resolveWith(g,[g])};"string"!==typeof a&&(b=a,a=void 0);for(a=a||"fx";h--;)(c=v.get(g[h],a+"queueHooks"))&&c.empty&&(e++,c.empty.add(k));k();return f.promise(b)}});var Db=/[+-]?(?:\d*\.|)\d+(?:[eE][+-]?\d+|)/.source,wa=new RegExp("^(?:([+-])=|)("+
Db+")([a-z%]*)$","i"),Z=["Top","Right","Bottom","Left"],ua=x.documentElement,ca=function(a){return d.contains(a.ownerDocument,a)},mc={composed:!0};ua.getRootNode&&(ca=function(a){return d.contains(a.ownerDocument,a)||a.getRootNode(mc)===a.ownerDocument});var Ma=function(a,b){a=b||a;return"none"===a.style.display||""===a.style.display&&ca(a)&&"none"===d.css(a,"display")},Eb=function(a,b,c,d){var e,g={};for(e in b)g[e]=a.style[e],a.style[e]=b[e];c=c.apply(a,d||[]);for(e in b)a.style[e]=g[e];return c},
ib={};d.fn.extend({show:function(){return xa(this,!0)},hide:function(){return xa(this)},toggle:function(a){return"boolean"===typeof a?a?this.show():this.hide():this.each(function(){Ma(this)?d(this).show():d(this).hide()})}});var la=/^(?:checkbox|radio)$/i,jb=/<([a-z][^\/\0>\x20\t\r\n\f]*)/i,kb=/^$|^module$|\/(?:java|ecma)script/i,S={option:[1,"<select multiple='multiple'>","</select>"],thead:[1,"<table>","</table>"],col:[2,"<table><colgroup>","</colgroup></table>"],tr:[2,"<table><tbody>","</tbody></table>"],
td:[3,"<table><tbody><tr>","</tr></tbody></table>"],_default:[0,"",""]};S.optgroup=S.option;S.tbody=S.tfoot=S.colgroup=S.caption=S.thead;S.th=S.td;var Ub=/<|&#?\w+;/;(function(){var a=x.createDocumentFragment().appendChild(x.createElement("div")),b=x.createElement("input");b.setAttribute("type","radio");b.setAttribute("checked","checked");b.setAttribute("name","t");a.appendChild(b);z.checkClone=a.cloneNode(!0).cloneNode(!0).lastChild.checked;a.innerHTML="<textarea>x</textarea>";z.noCloneChecked=!!a.cloneNode(!0).lastChild.defaultValue})();
var nc=/^key/,oc=/^(?:mouse|pointer|contextmenu|drag|drop)|click/,Fb=/^([^.]*)(?:\.(.+)|)/;d.event={global:{},add:function(a,b,c,e,f){var g,h,k,l,n;if(k=v.get(a)){if(c.handler){var m=c;c=m.handler;f=m.selector}f&&d.find.matchesSelector(ua,f);c.guid||(c.guid=d.guid++);(h=k.events)||(h=k.events={});(g=k.handle)||(g=k.handle=function(b){return"undefined"!==typeof d&&d.event.triggered!==b.type?d.event.dispatch.apply(a,arguments):void 0});b=(b||"").match(ba)||[""];for(k=b.length;k--;){var p=Fb.exec(b[k])||
[];var q=l=p[1];var r=(p[2]||"").split(".").sort();q&&(p=d.event.special[q]||{},q=(f?p.delegateType:p.bindType)||q,p=d.event.special[q]||{},l=d.extend({type:q,origType:l,data:e,handler:c,guid:c.guid,selector:f,needsContext:f&&d.expr.match.needsContext.test(f),namespace:r.join(".")},m),(n=h[q])||(n=h[q]=[],n.delegateCount=0,p.setup&&!1!==p.setup.call(a,e,r,g)||a.addEventListener&&a.addEventListener(q,g)),p.add&&(p.add.call(a,l),l.handler.guid||(l.handler.guid=c.guid)),f?n.splice(n.delegateCount++,
0,l):n.push(l),d.event.global[q]=!0)}}},remove:function(a,b,c,e,f){var g,h,k,l,n,m=v.hasData(a)&&v.get(a);if(m&&(k=m.events)){b=(b||"").match(ba)||[""];for(l=b.length;l--;){var p=Fb.exec(b[l])||[];var q=n=p[1];var r=(p[2]||"").split(".").sort();if(q){var t=d.event.special[q]||{};q=(e?t.delegateType:t.bindType)||q;var x=k[q]||[];p=p[2]&&new RegExp("(^|\\.)"+r.join("\\.(?:.*\\.|)")+"(\\.|$)");for(h=g=x.length;g--;){var u=x[g];!f&&n!==u.origType||c&&c.guid!==u.guid||p&&!p.test(u.namespace)||e&&e!==u.selector&&
("**"!==e||!u.selector)||(x.splice(g,1),u.selector&&x.delegateCount--,t.remove&&t.remove.call(a,u))}h&&!x.length&&(t.teardown&&!1!==t.teardown.call(a,r,m.handle)||d.removeEvent(a,q,m.handle),delete k[q])}else for(q in k)d.event.remove(a,q+b[l],c,e,!0)}d.isEmptyObject(k)&&v.remove(a,"handle events")}},dispatch:function(a){var b=d.event.fix(a),c,e,f,g=Array(arguments.length);var h=(v.get(this,"events")||{})[b.type]||[];var k=d.event.special[b.type]||{};g[0]=b;for(c=1;c<arguments.length;c++)g[c]=arguments[c];
b.delegateTarget=this;if(!k.preDispatch||!1!==k.preDispatch.call(this,b)){var l=d.event.handlers.call(this,b,h);for(c=0;(f=l[c++])&&!b.isPropagationStopped();)for(b.currentTarget=f.elem,h=0;(e=f.handlers[h++])&&!b.isImmediatePropagationStopped();)if(!b.rnamespace||!1===e.namespace||b.rnamespace.test(e.namespace))b.handleObj=e,b.data=e.data,e=((d.event.special[e.origType]||{}).handle||e.handler).apply(f.elem,g),void 0!==e&&!1===(b.result=e)&&(b.preventDefault(),b.stopPropagation());k.postDispatch&&
k.postDispatch.call(this,b);return b.result}},handlers:function(a,b){var c,e=[],f=b.delegateCount,g=a.target;if(f&&g.nodeType&&!("click"===a.type&&1<=a.button))for(;g!==this;g=g.parentNode||this)if(1===g.nodeType&&("click"!==a.type||!0!==g.disabled)){var h=[];var k={};for(c=0;c<f;c++){var l=b[c];var n=l.selector+" ";void 0===k[n]&&(k[n]=l.needsContext?-1<d(n,this).index(g):d.find(n,this,null,[g]).length);k[n]&&h.push(l)}h.length&&e.push({elem:g,handlers:h})}f<b.length&&e.push({elem:this,handlers:b.slice(f)});
return e},addProp:function(a,b){Object.defineProperty(d.Event.prototype,a,{enumerable:!0,configurable:!0,get:t(b)?function(){if(this.originalEvent)return b(this.originalEvent)}:function(){if(this.originalEvent)return this.originalEvent[a]},set:function(b){Object.defineProperty(this,a,{enumerable:!0,configurable:!0,writable:!0,value:b})}})},fix:function(a){return a[d.expando]?a:new d.Event(a)},special:{load:{noBubble:!0},click:{setup:function(a){a=this||a;la.test(a.type)&&a.click&&M(a,"input")&&Oa(a,
"click",ya);return!1},trigger:function(a){a=this||a;la.test(a.type)&&a.click&&M(a,"input")&&Oa(a,"click");return!0},_default:function(a){a=a.target;return la.test(a.type)&&a.click&&M(a,"input")&&v.get(a,"click")||M(a,"a")}},beforeunload:{postDispatch:function(a){void 0!==a.result&&a.originalEvent&&(a.originalEvent.returnValue=a.result)}}}};d.removeEvent=function(a,b,c){a.removeEventListener&&a.removeEventListener(b,c)};d.Event=function(a,b){if(!(this instanceof d.Event))return new d.Event(a,b);a&&
a.type?(this.originalEvent=a,this.type=a.type,this.isDefaultPrevented=a.defaultPrevented||void 0===a.defaultPrevented&&!1===a.returnValue?ya:ma,this.target=a.target&&3===a.target.nodeType?a.target.parentNode:a.target,this.currentTarget=a.currentTarget,this.relatedTarget=a.relatedTarget):this.type=a;b&&d.extend(this,b);this.timeStamp=a&&a.timeStamp||Date.now();this[d.expando]=!0};d.Event.prototype={constructor:d.Event,isDefaultPrevented:ma,isPropagationStopped:ma,isImmediatePropagationStopped:ma,isSimulated:!1,
preventDefault:function(){var a=this.originalEvent;this.isDefaultPrevented=ya;a&&!this.isSimulated&&a.preventDefault()},stopPropagation:function(){var a=this.originalEvent;this.isPropagationStopped=ya;a&&!this.isSimulated&&a.stopPropagation()},stopImmediatePropagation:function(){var a=this.originalEvent;this.isImmediatePropagationStopped=ya;a&&!this.isSimulated&&a.stopImmediatePropagation();this.stopPropagation()}};d.each({altKey:!0,bubbles:!0,cancelable:!0,changedTouches:!0,ctrlKey:!0,detail:!0,
eventPhase:!0,metaKey:!0,pageX:!0,pageY:!0,shiftKey:!0,view:!0,"char":!0,code:!0,charCode:!0,key:!0,keyCode:!0,button:!0,buttons:!0,clientX:!0,clientY:!0,offsetX:!0,offsetY:!0,pointerId:!0,pointerType:!0,screenX:!0,screenY:!0,targetTouches:!0,toElement:!0,touches:!0,which:function(a){var b=a.button;return null==a.which&&nc.test(a.type)?null!=a.charCode?a.charCode:a.keyCode:!a.which&&void 0!==b&&oc.test(a.type)?b&1?1:b&2?3:b&4?2:0:a.which}},d.event.addProp);d.each({focus:"focusin",blur:"focusout"},
function(a,b){d.event.special[a]={setup:function(){Oa(this,a,Vb);return!1},trigger:function(){Oa(this,a);return!0},delegateType:b}});d.each({mouseenter:"mouseover",mouseleave:"mouseout",pointerenter:"pointerover",pointerleave:"pointerout"},function(a,b){d.event.special[a]={delegateType:b,bindType:b,handle:function(a){var c=a.relatedTarget,f=a.handleObj;if(!c||c!==this&&!d.contains(this,c)){a.type=f.origType;var g=f.handler.apply(this,arguments);a.type=b}return g}}});d.fn.extend({on:function(a,b,c,
d){return Ua(this,a,b,c,d)},one:function(a,b,c,d){return Ua(this,a,b,c,d,1)},off:function(a,b,c){if(a&&a.preventDefault&&a.handleObj){var e=a.handleObj;d(a.delegateTarget).off(e.namespace?e.origType+"."+e.namespace:e.origType,e.selector,e.handler);return this}if("object"===typeof a){for(e in a)this.off(e,b,a[e]);return this}if(!1===b||"function"===typeof b)c=b,b=void 0;!1===c&&(c=ma);return this.each(function(){d.event.remove(this,a,c,b)})}});var pc=/<(?!area|br|col|embed|hr|img|input|link|meta|param)(([a-z][^\/\0>\x20\t\r\n\f]*)[^>]*)\/>/gi,
qc=/<script|<style|<link/i,Yb=/checked\s*(?:[^=]|=\s*.checked.)/i,$b=/^\s*<!(?:\[CDATA\[|--)|(?:\]\]|--)>\s*$/g;d.extend({htmlPrefilter:function(a){return a.replace(pc,"<$1></$2>")},clone:function(a,b,c){var e,f=a.cloneNode(!0),g=ca(a);if(!(z.noCloneChecked||1!==a.nodeType&&11!==a.nodeType||d.isXMLDoc(a))){var h=T(f);var k=T(a);var l=0;for(e=k.length;l<e;l++){var n=k[l],m=h[l],p=m.nodeName.toLowerCase();if("input"===p&&la.test(n.type))m.checked=n.checked;else if("input"===p||"textarea"===p)m.defaultValue=
n.defaultValue}}if(b)if(c)for(k=k||T(a),h=h||T(f),l=0,e=k.length;l<e;l++)mb(k[l],h[l]);else mb(a,f);h=T(f,"script");0<h.length&&Fa(h,!g&&T(a,"script"));return f},cleanData:function(a){for(var b,c,e,f=d.event.special,g=0;void 0!==(c=a[g]);g++)if(Ta(c)){if(b=c[v.expando]){if(b.events)for(e in b.events)f[e]?d.event.remove(c,e):d.removeEvent(c,e,b.handle);c[v.expando]=void 0}c[P.expando]&&(c[P.expando]=void 0)}}});d.fn.extend({detach:function(a){return ob(this,a,!0)},remove:function(a){return ob(this,
a)},text:function(a){return ia(this,function(a){return void 0===a?d.text(this):this.empty().each(function(){if(1===this.nodeType||11===this.nodeType||9===this.nodeType)this.textContent=a})},null,a,arguments.length)},append:function(){return za(this,arguments,function(a){1!==this.nodeType&&11!==this.nodeType&&9!==this.nodeType||lb(this,a).appendChild(a)})},prepend:function(){return za(this,arguments,function(a){if(1===this.nodeType||11===this.nodeType||9===this.nodeType){var b=lb(this,a);b.insertBefore(a,
b.firstChild)}})},before:function(){return za(this,arguments,function(a){this.parentNode&&this.parentNode.insertBefore(a,this)})},after:function(){return za(this,arguments,function(a){this.parentNode&&this.parentNode.insertBefore(a,this.nextSibling)})},empty:function(){for(var a,b=0;null!=(a=this[b]);b++)1===a.nodeType&&(d.cleanData(T(a,!1)),a.textContent="");return this},clone:function(a,b){a=null==a?!1:a;b=null==b?a:b;return this.map(function(){return d.clone(this,a,b)})},html:function(a){return ia(this,
function(a){var b=this[0]||{},e=0,f=this.length;if(void 0===a&&1===b.nodeType)return b.innerHTML;if("string"===typeof a&&!qc.test(a)&&!S[(jb.exec(a)||["",""])[1].toLowerCase()]){a=d.htmlPrefilter(a);try{for(;e<f;e++)b=this[e]||{},1===b.nodeType&&(d.cleanData(T(b,!1)),b.innerHTML=a);b=0}catch(g){}}b&&this.empty().append(a)},null,a,arguments.length)},replaceWith:function(){var a=[];return za(this,arguments,function(b){var c=this.parentNode;0>d.inArray(this,a)&&(d.cleanData(T(this)),c&&c.replaceChild(b,
this))},a)}});d.each({appendTo:"append",prependTo:"prepend",insertBefore:"before",insertAfter:"after",replaceAll:"replaceWith"},function(a,b){d.fn[a]=function(a){for(var c=[],f=d(a),g=f.length-1,h=0;h<=g;h++)a=h===g?this:this.clone(!0),d(f[h])[b](a),cb.apply(c,a.get());return this.pushStack(c)}});var Va=new RegExp("^("+Db+")(?!px)[a-z%]+$","i"),Pa=function(a){var b=a.ownerDocument.defaultView;b&&b.opener||(b=m);return b.getComputedStyle(a)},ac=new RegExp(Z.join("|"),"i");(function(){function a(){if(k){h.style.cssText=
"position:absolute;left:-11111px;width:60px;margin-top:1px;padding:0;border:0";k.style.cssText="position:relative;display:block;box-sizing:border-box;overflow:scroll;margin:auto;border:1px;padding:1px;width:60%;top:1%";ua.appendChild(h).appendChild(k);var a=m.getComputedStyle(k);b="1%"!==a.top;g=12===Math.round(parseFloat(a.marginLeft));k.style.right="60%";f=36===Math.round(parseFloat(a.right));c=36===Math.round(parseFloat(a.width));k.style.position="absolute";e=12===Math.round(parseFloat(k.offsetWidth/
3));ua.removeChild(h);k=null}}var b,c,e,f,g,h=x.createElement("div"),k=x.createElement("div");k.style&&(k.style.backgroundClip="content-box",k.cloneNode(!0).style.backgroundClip="",z.clearCloneStyle="content-box"===k.style.backgroundClip,d.extend(z,{boxSizingReliable:function(){a();return c},pixelBoxStyles:function(){a();return f},pixelPosition:function(){a();return b},reliableMarginLeft:function(){a();return g},scrollboxSize:function(){a();return e}}))})();var sb=["Webkit","Moz","ms"],rb=x.createElement("div").style,
qb={},rc=/^(none|table(?!-c[ea]).+)/,Gb=/^--/,sc={position:"absolute",visibility:"hidden",display:"block"},Hb={letterSpacing:"0",fontWeight:"400"};d.extend({cssHooks:{opacity:{get:function(a,b){if(b)return a=Ca(a,"opacity"),""===a?"1":a}}},cssNumber:{animationIterationCount:!0,columnCount:!0,fillOpacity:!0,flexGrow:!0,flexShrink:!0,fontWeight:!0,gridArea:!0,gridColumn:!0,gridColumnEnd:!0,gridColumnStart:!0,gridRow:!0,gridRowEnd:!0,gridRowStart:!0,lineHeight:!0,opacity:!0,order:!0,orphans:!0,widows:!0,
zIndex:!0,zoom:!0},cssProps:{},style:function(a,b,c,e){if(a&&3!==a.nodeType&&8!==a.nodeType&&a.style){var f,g=u(b),h=Gb.test(b),k=a.style;h||(b=Wa(g));var l=d.cssHooks[b]||d.cssHooks[g];if(void 0!==c){var n=typeof c;"string"===n&&(f=wa.exec(c))&&f[1]&&(c=Ka(a,b,f),n="number");null!=c&&c===c&&("number"!==n||h||(c+=f&&f[3]||(d.cssNumber[g]?"":"px")),z.clearCloneStyle||""!==c||0!==b.indexOf("background")||(k[b]="inherit"),l&&"set"in l&&void 0===(c=l.set(a,c,e))||(h?k.setProperty(b,c):k[b]=c))}else return l&&
"get"in l&&void 0!==(f=l.get(a,!1,e))?f:k[b]}},css:function(a,b,c,e){var f;var g=u(b);Gb.test(b)||(b=Wa(g));(g=d.cssHooks[b]||d.cssHooks[g])&&"get"in g&&(f=g.get(a,!0,c));void 0===f&&(f=Ca(a,b,e));"normal"===f&&b in Hb&&(f=Hb[b]);return""===c||c?(a=parseFloat(f),!0===c||isFinite(a)?a||0:f):f}});d.each(["height","width"],function(a,b){d.cssHooks[b]={get:function(a,e,f){if(e)return!rc.test(d.css(a,"display"))||a.getClientRects().length&&a.getBoundingClientRect().width?ub(a,b,f):Eb(a,sc,function(){return ub(a,
b,f)})},set:function(a,e,f){var c,h=Pa(a),k=!z.scrollboxSize()&&"absolute"===h.position,l=(k||f)&&"border-box"===d.css(a,"boxSizing",!1,h);f=f?Xa(a,b,f,l,h):0;l&&k&&(f-=Math.ceil(a["offset"+b[0].toUpperCase()+b.slice(1)]-parseFloat(h[b])-Xa(a,b,"border",!1,h)-.5));f&&(c=wa.exec(e))&&"px"!==(c[3]||"px")&&(a.style[b]=e,e=d.css(a,b));return tb(a,e,f)}}});d.cssHooks.marginLeft=pb(z.reliableMarginLeft,function(a,b){if(b)return(parseFloat(Ca(a,"marginLeft"))||a.getBoundingClientRect().left-Eb(a,{marginLeft:0},
function(){return a.getBoundingClientRect().left}))+"px"});d.each({margin:"",padding:"",border:"Width"},function(a,b){d.cssHooks[a+b]={expand:function(c){var d=0,f={};for(c="string"===typeof c?c.split(" "):[c];4>d;d++)f[a+Z[d]+b]=c[d]||c[d-2]||c[0];return f}};"margin"!==a&&(d.cssHooks[a+b].set=tb)});d.fn.extend({css:function(a,b){return ia(this,function(a,b,f){var c,e={},k=0;if(Array.isArray(b)){f=Pa(a);for(c=b.length;k<c;k++)e[b[k]]=d.css(a,b[k],!1,f);return e}return void 0!==f?d.style(a,b,f):d.css(a,
b)},a,b,1<arguments.length)}});d.Tween=Y;Y.prototype={constructor:Y,init:function(a,b,c,e,f,g){this.elem=a;this.prop=c;this.easing=f||d.easing._default;this.options=b;this.start=this.now=this.cur();this.end=e;this.unit=g||(d.cssNumber[c]?"":"px")},cur:function(){var a=Y.propHooks[this.prop];return a&&a.get?a.get(this):Y.propHooks._default.get(this)},run:function(a){var b,c=Y.propHooks[this.prop];this.pos=this.options.duration?b=d.easing[this.easing](a,this.options.duration*a,0,1,this.options.duration):
b=a;this.now=(this.end-this.start)*b+this.start;this.options.step&&this.options.step.call(this.elem,this.now,this);c&&c.set?c.set(this):Y.propHooks._default.set(this);return this}};Y.prototype.init.prototype=Y.prototype;Y.propHooks={_default:{get:function(a){return 1!==a.elem.nodeType||null!=a.elem[a.prop]&&null==a.elem.style[a.prop]?a.elem[a.prop]:(a=d.css(a.elem,a.prop,""))&&"auto"!==a?a:0},set:function(a){if(d.fx.step[a.prop])d.fx.step[a.prop](a);else 1!==a.elem.nodeType||!d.cssHooks[a.prop]&&
null==a.elem.style[Wa(a.prop)]?a.elem[a.prop]=a.now:d.style(a.elem,a.prop,a.now+a.unit)}}};Y.propHooks.scrollTop=Y.propHooks.scrollLeft={set:function(a){a.elem.nodeType&&a.elem.parentNode&&(a.elem[a.prop]=a.now)}};d.easing={linear:function(a){return a},swing:function(a){return.5-Math.cos(a*Math.PI)/2},_default:"swing"};d.fx=Y.prototype.init;d.fx.step={};var ka,Qa,tc=/^(?:toggle|show|hide)$/,uc=/queueHooks$/;d.Animation=d.extend(U,{tweeners:{"*":[function(a,b){var c=this.createTween(a,b);Ka(c.elem,
a,wa.exec(b),c);return c}]},tweener:function(a,b){t(a)?(b=a,a=["*"]):a=a.match(ba);for(var c,d=0,f=a.length;d<f;d++)c=a[d],U.tweeners[c]=U.tweeners[c]||[],U.tweeners[c].unshift(b)},prefilters:[function(a,b,c){var e;var f="width"in b||"height"in b;var g=this,h={},k=a.style,l=a.nodeType&&Ma(a),n=v.get(a,"fxshow");if(!c.queue){var m=d._queueHooks(a,"fx");if(null==m.unqueued){m.unqueued=0;var p=m.empty.fire;m.empty.fire=function(){m.unqueued||p()}}m.unqueued++;g.always(function(){g.always(function(){m.unqueued--;
d.queue(a,"fx").length||m.empty.fire()})})}for(e in b){var q=b[e];if(tc.test(q)){delete b[e];var r=r||"toggle"===q;if(q===(l?"hide":"show"))if("show"===q&&n&&void 0!==n[e])l=!0;else continue;h[e]=n&&n[e]||d.style(a,e)}}if((b=!d.isEmptyObject(b))||!d.isEmptyObject(h)){if(f&&1===a.nodeType){c.overflow=[k.overflow,k.overflowX,k.overflowY];var t=n&&n.display;null==t&&(t=v.get(a,"display"));f=d.css(a,"display");"none"===f&&(t?f=t:(xa([a],!0),t=a.style.display||t,f=d.css(a,"display"),xa([a])));("inline"===
f||"inline-block"===f&&null!=t)&&"none"===d.css(a,"float")&&(b||(g.done(function(){k.display=t}),null==t&&(f=k.display,t="none"===f?"":f)),k.display="inline-block")}c.overflow&&(k.overflow="hidden",g.always(function(){k.overflow=c.overflow[0];k.overflowX=c.overflow[1];k.overflowY=c.overflow[2]}));b=!1;for(e in h)b||(n?"hidden"in n&&(l=n.hidden):n=v.access(a,"fxshow",{display:t}),r&&(n.hidden=!l),l&&xa([a],!0),g.done(function(){l||xa([a]);v.remove(a,"fxshow");for(e in h)d.style(a,e,h[e])})),b=wb(l?
n[e]:0,e,g),e in n||(n[e]=b.start,l&&(b.end=b.start,b.start=0))}}],prefilter:function(a,b){b?U.prefilters.unshift(a):U.prefilters.push(a)}});d.speed=function(a,b,c){var e=a&&"object"===typeof a?d.extend({},a):{complete:c||!c&&b||t(a)&&a,duration:a,easing:c&&b||b&&!t(b)&&b};d.fx.off?e.duration=0:"number"!==typeof e.duration&&(e.duration=e.duration in d.fx.speeds?d.fx.speeds[e.duration]:d.fx.speeds._default);if(null==e.queue||!0===e.queue)e.queue="fx";e.old=e.complete;e.complete=function(){t(e.old)&&
e.old.call(this);e.queue&&d.dequeue(this,e.queue)};return e};d.fn.extend({fadeTo:function(a,b,c,d){return this.filter(Ma).css("opacity",0).show().end().animate({opacity:b},a,c,d)},animate:function(a,b,c,e){var f=d.isEmptyObject(a),g=d.speed(b,c,e);b=function(){var b=U(this,d.extend({},a),g);(f||v.get(this,"finish"))&&b.stop(!0)};b.finish=b;return f||!1===g.queue?this.each(b):this.queue(g.queue,b)},stop:function(a,b,c){var e=function(a){var b=a.stop;delete a.stop;b(c)};"string"!==typeof a&&(c=b,b=
a,a=void 0);b&&!1!==a&&this.queue(a||"fx",[]);return this.each(function(){var b=!0,g=null!=a&&a+"queueHooks",h=d.timers,k=v.get(this);if(g)k[g]&&k[g].stop&&e(k[g]);else for(g in k)k[g]&&k[g].stop&&uc.test(g)&&e(k[g]);for(g=h.length;g--;)h[g].elem!==this||null!=a&&h[g].queue!==a||(h[g].anim.stop(c),b=!1,h.splice(g,1));!b&&c||d.dequeue(this,a)})},finish:function(a){!1!==a&&(a=a||"fx");return this.each(function(){var b=v.get(this),c=b[a+"queue"];var e=b[a+"queueHooks"];var f=d.timers,g=c?c.length:0;
b.finish=!0;d.queue(this,a,[]);e&&e.stop&&e.stop.call(this,!0);for(e=f.length;e--;)f[e].elem===this&&f[e].queue===a&&(f[e].anim.stop(!0),f.splice(e,1));for(e=0;e<g;e++)c[e]&&c[e].finish&&c[e].finish.call(this);delete b.finish})}});d.each(["toggle","show","hide"],function(a,b){var c=d.fn[b];d.fn[b]=function(a,d,g){return null==a||"boolean"===typeof a?c.apply(this,arguments):this.animate(Ra(b,!0),a,d,g)}});d.each({slideDown:Ra("show"),slideUp:Ra("hide"),slideToggle:Ra("toggle"),fadeIn:{opacity:"show"},
fadeOut:{opacity:"hide"},fadeToggle:{opacity:"toggle"}},function(a,b){d.fn[a]=function(a,d,f){return this.animate(b,a,d,f)}});d.timers=[];d.fx.tick=function(){var a=0,b=d.timers;for(ka=Date.now();a<b.length;a++){var c=b[a];c()||b[a]!==c||b.splice(a--,1)}b.length||d.fx.stop();ka=void 0};d.fx.timer=function(a){d.timers.push(a);d.fx.start()};d.fx.interval=13;d.fx.start=function(){Qa||(Qa=!0,Ya())};d.fx.stop=function(){Qa=null};d.fx.speeds={slow:600,fast:200,_default:400};d.fn.delay=function(a,b){a=d.fx?
d.fx.speeds[a]||a:a;return this.queue(b||"fx",function(b,d){var c=m.setTimeout(b,a);d.stop=function(){m.clearTimeout(c)}})};(function(){var a=x.createElement("input"),b=x.createElement("select").appendChild(x.createElement("option"));a.type="checkbox";z.checkOn=""!==a.value;z.optSelected=b.selected;a=x.createElement("input");a.value="t";a.type="radio";z.radioValue="t"===a.value})();var Aa=d.expr.attrHandle;d.fn.extend({attr:function(a,b){return ia(this,d.attr,a,b,1<arguments.length)},removeAttr:function(a){return this.each(function(){d.removeAttr(this,
a)})}});d.extend({attr:function(a,b,c){var e,f,g=a.nodeType;if(3!==g&&8!==g&&2!==g){if("undefined"===typeof a.getAttribute)return d.prop(a,b,c);1===g&&d.isXMLDoc(a)||(f=d.attrHooks[b.toLowerCase()]||(d.expr.match.bool.test(b)?vc:void 0));if(void 0!==c){if(null===c){d.removeAttr(a,b);return}if(f&&"set"in f&&void 0!==(e=f.set(a,c,b)))return e;a.setAttribute(b,c+"");return c}if(f&&"get"in f&&null!==(e=f.get(a,b)))return e;e=d.find.attr(a,b);return null==e?void 0:e}},attrHooks:{type:{set:function(a,b){if(!z.radioValue&&
"radio"===b&&M(a,"input")){var c=a.value;a.setAttribute("type",b);c&&(a.value=c);return b}}}},removeAttr:function(a,b){var c=0,d=b&&b.match(ba);if(d&&1===a.nodeType)for(;b=d[c++];)a.removeAttribute(b)}});var vc={set:function(a,b,c){!1===b?d.removeAttr(a,c):a.setAttribute(c,c);return c}};d.each(d.expr.match.bool.source.match(/\w+/g),function(a,b){var c=Aa[b]||d.find.attr;Aa[b]=function(a,b,d){var e=b.toLowerCase();if(!d){var f=Aa[e];Aa[e]=g;var g=null!=c(a,b,d)?e:null;Aa[e]=f}return g}});var wc=/^(?:input|select|textarea|button)$/i,
xc=/^(?:a|area)$/i;d.fn.extend({prop:function(a,b){return ia(this,d.prop,a,b,1<arguments.length)},removeProp:function(a){return this.each(function(){delete this[d.propFix[a]||a]})}});d.extend({prop:function(a,b,c){var e,f=a.nodeType;if(3!==f&&8!==f&&2!==f){if(1!==f||!d.isXMLDoc(a)){b=d.propFix[b]||b;var g=d.propHooks[b]}return void 0!==c?g&&"set"in g&&void 0!==(e=g.set(a,c,b))?e:a[b]=c:g&&"get"in g&&null!==(e=g.get(a,b))?e:a[b]}},propHooks:{tabIndex:{get:function(a){var b=d.find.attr(a,"tabindex");
return b?parseInt(b,10):wc.test(a.nodeName)||xc.test(a.nodeName)&&a.href?0:-1}}},propFix:{"for":"htmlFor","class":"className"}});z.optSelected||(d.propHooks.selected={get:function(a){(a=a.parentNode)&&a.parentNode&&a.parentNode.selectedIndex;return null},set:function(a){if(a=a.parentNode)a.selectedIndex,a.parentNode&&a.parentNode.selectedIndex}});d.each("tabIndex readOnly maxLength cellSpacing cellPadding rowSpan colSpan useMap frameBorder contentEditable".split(" "),function(){d.propFix[this.toLowerCase()]=
this});d.fn.extend({addClass:function(a){var b,c,e,f,g=0;if(t(a))return this.each(function(b){d(this).addClass(a.call(this,b,da(this)))});var h=Za(a);if(h.length)for(;b=this[g++];){var k=da(b);if(c=1===b.nodeType&&" "+na(k)+" "){for(f=0;e=h[f++];)0>c.indexOf(" "+e+" ")&&(c+=e+" ");c=na(c);k!==c&&b.setAttribute("class",c)}}return this},removeClass:function(a){var b,c,e,f,g=0;if(t(a))return this.each(function(b){d(this).removeClass(a.call(this,b,da(this)))});if(!arguments.length)return this.attr("class",
"");var h=Za(a);if(h.length)for(;b=this[g++];){var k=da(b);if(c=1===b.nodeType&&" "+na(k)+" "){for(f=0;e=h[f++];)for(;-1<c.indexOf(" "+e+" ");)c=c.replace(" "+e+" "," ");c=na(c);k!==c&&b.setAttribute("class",c)}}return this},toggleClass:function(a,b){var c=typeof a,e="string"===c||Array.isArray(a);return"boolean"===typeof b&&e?b?this.addClass(a):this.removeClass(a):t(a)?this.each(function(c){d(this).toggleClass(a.call(this,c,da(this),b),b)}):this.each(function(){var b,g;if(e){var h=0;var k=d(this);
for(g=Za(a);b=g[h++];)k.hasClass(b)?k.removeClass(b):k.addClass(b)}else if(void 0===a||"boolean"===c)(b=da(this))&&v.set(this,"__className__",b),this.setAttribute&&this.setAttribute("class",b||!1===a?"":v.get(this,"__className__")||"")})},hasClass:function(a){var b,c=0;for(a=" "+a+" ";b=this[c++];)if(1===b.nodeType&&-1<(" "+na(da(b))+" ").indexOf(a))return!0;return!1}});var yc=/\r/g;d.fn.extend({val:function(a){var b,c,e=this[0];if(arguments.length){var f=t(a);return this.each(function(c){1===this.nodeType&&
(c=f?a.call(this,c,d(this).val()):a,null==c?c="":"number"===typeof c?c+="":Array.isArray(c)&&(c=d.map(c,function(a){return null==a?"":a+""})),b=d.valHooks[this.type]||d.valHooks[this.nodeName.toLowerCase()],b&&"set"in b&&void 0!==b.set(this,c,"value")||(this.value=c))})}if(e){if((b=d.valHooks[e.type]||d.valHooks[e.nodeName.toLowerCase()])&&"get"in b&&void 0!==(c=b.get(e,"value")))return c;c=e.value;return"string"===typeof c?c.replace(yc,""):null==c?"":c}}});d.extend({valHooks:{option:{get:function(a){var b=
d.find.attr(a,"value");return null!=b?b:na(d.text(a))}},select:{get:function(a){var b=a.options,c=a.selectedIndex,e="select-one"===a.type,f=e?null:[],g=e?c+1:b.length;for(a=0>c?g:e?c:0;a<g;a++){var h=b[a];if(!(!h.selected&&a!==c||h.disabled||h.parentNode.disabled&&M(h.parentNode,"optgroup"))){h=d(h).val();if(e)return h;f.push(h)}}return f},set:function(a,b){for(var c,e=a.options,f=d.makeArray(b),g=e.length;g--;)if(b=e[g],b.selected=-1<d.inArray(d.valHooks.option.get(b),f))c=!0;c||(a.selectedIndex=
-1);return f}}}});d.each(["radio","checkbox"],function(){d.valHooks[this]={set:function(a,b){if(Array.isArray(b))return a.checked=-1<d.inArray(d(a).val(),b)}};z.checkOn||(d.valHooks[this].get=function(a){return null===a.getAttribute("value")?"on":a.value})});z.focusin="onfocusin"in m;var Ib=/^(?:focusinfocus|focusoutblur)$/,Jb=function(a){a.stopPropagation()};d.extend(d.event,{trigger:function(a,b,c,e){var f,g,h,k=[c||x],l=Sa.call(a,"type")?a.type:a;var n=Sa.call(a,"namespace")?a.namespace.split("."):
[];var p=h=f=c=c||x;if(3!==c.nodeType&&8!==c.nodeType&&!Ib.test(l+d.event.triggered)){-1<l.indexOf(".")&&(n=l.split("."),l=n.shift(),n.sort());var q=0>l.indexOf(":")&&"on"+l;a=a[d.expando]?a:new d.Event(l,"object"===typeof a&&a);a.isTrigger=e?2:3;a.namespace=n.join(".");a.rnamespace=a.namespace?new RegExp("(^|\\.)"+n.join("\\.(?:.*\\.|)")+"(\\.|$)"):null;a.result=void 0;a.target||(a.target=c);b=null==b?[a]:d.makeArray(b,[a]);n=d.event.special[l]||{};if(e||!n.trigger||!1!==n.trigger.apply(c,b)){if(!e&&
!n.noBubble&&!va(c)){var r=n.delegateType||l;Ib.test(r+l)||(p=p.parentNode);for(;p;p=p.parentNode)k.push(p),f=p;f===(c.ownerDocument||x)&&k.push(f.defaultView||f.parentWindow||m)}for(f=0;(p=k[f++])&&!a.isPropagationStopped();)h=p,a.type=1<f?r:n.bindType||l,(g=(v.get(p,"events")||{})[a.type]&&v.get(p,"handle"))&&g.apply(p,b),(g=q&&p[q])&&g.apply&&Ta(p)&&(a.result=g.apply(p,b),!1===a.result&&a.preventDefault());a.type=l;e||a.isDefaultPrevented()||n._default&&!1!==n._default.apply(k.pop(),b)||!Ta(c)||
!q||!t(c[l])||va(c)||((f=c[q])&&(c[q]=null),d.event.triggered=l,a.isPropagationStopped()&&h.addEventListener(l,Jb),c[l](),a.isPropagationStopped()&&h.removeEventListener(l,Jb),d.event.triggered=void 0,f&&(c[q]=f));return a.result}}},simulate:function(a,b,c){a=d.extend(new d.Event,c,{type:a,isSimulated:!0});d.event.trigger(a,null,b)}});d.fn.extend({trigger:function(a,b){return this.each(function(){d.event.trigger(a,b,this)})},triggerHandler:function(a,b){var c=this[0];if(c)return d.event.trigger(a,
b,c,!0)}});z.focusin||d.each({focus:"focusin",blur:"focusout"},function(a,b){var c=function(a){d.event.simulate(b,a.target,d.event.fix(a))};d.event.special[b]={setup:function(){var d=this.ownerDocument||this,f=v.access(d,b);f||d.addEventListener(a,c,!0);v.access(d,b,(f||0)+1)},teardown:function(){var d=this.ownerDocument||this,f=v.access(d,b)-1;f?v.access(d,b,f):(d.removeEventListener(a,c,!0),v.remove(d,b))}}});var Ea=m.location,Kb=Date.now(),eb=/\?/;d.parseXML=function(a){if(!a||"string"!==typeof a)return null;
try{var b=(new m.DOMParser).parseFromString(a,"text/xml")}catch(c){b=void 0}b&&!b.getElementsByTagName("parsererror").length||d.error("Invalid XML: "+a);return b};var cc=/\[\]$/,Lb=/\r?\n/g,zc=/^(?:submit|button|image|reset|file)$/i,Ac=/^(?:input|select|textarea|keygen)/i;d.param=function(a,b){var c,e=[],f=function(a,b){b=t(b)?b():b;e[e.length]=encodeURIComponent(a)+"="+encodeURIComponent(null==b?"":b)};if(null==a)return"";if(Array.isArray(a)||a.jquery&&!d.isPlainObject(a))d.each(a,function(){f(this.name,
this.value)});else for(c in a)$a(c,a[c],b,f);return e.join("&")};d.fn.extend({serialize:function(){return d.param(this.serializeArray())},serializeArray:function(){return this.map(function(){var a=d.prop(this,"elements");return a?d.makeArray(a):this}).filter(function(){var a=this.type;return this.name&&!d(this).is(":disabled")&&Ac.test(this.nodeName)&&!zc.test(a)&&(this.checked||!la.test(a))}).map(function(a,b){a=d(this).val();return null==a?null:Array.isArray(a)?d.map(a,function(a){return{name:b.name,
value:a.replace(Lb,"\r\n")}}):{name:b.name,value:a.replace(Lb,"\r\n")}}).get()}});var Bc=/%20/g,Cc=/#.*$/,Dc=/([?&])_=[^&]*/,Ec=/^(.*?):[ \t]*([^\r\n]*)$/mg,Fc=/^(?:GET|HEAD)$/,Gc=/^\/\//,Mb={},ab={},Nb="*/".concat("*"),fb=x.createElement("a");fb.href=Ea.href;d.extend({active:0,lastModified:{},etag:{},ajaxSettings:{url:Ea.href,type:"GET",isLocal:/^(?:about|app|app-storage|.+-extension|file|res|widget):$/.test(Ea.protocol),global:!0,processData:!0,async:!0,contentType:"application/x-www-form-urlencoded; charset=UTF-8",
accepts:{"*":Nb,text:"text/plain",html:"text/html",xml:"application/xml, text/xml",json:"application/json, text/javascript"},contents:{xml:/\bxml\b/,html:/\bhtml/,json:/\bjson\b/},responseFields:{xml:"responseXML",text:"responseText",json:"responseJSON"},converters:{"* text":String,"text html":!0,"text json":JSON.parse,"text xml":d.parseXML},flatOptions:{url:!0,context:!0}},ajaxSetup:function(a,b){return b?bb(bb(a,d.ajaxSettings),b):bb(d.ajaxSettings,a)},ajaxPrefilter:xb(Mb),ajaxTransport:xb(ab),
ajax:function(a,b){function c(a,b,c,g){var l=b;if(!y){y=!0;h&&m.clearTimeout(h);e=void 0;f=g||"";E.readyState=0<a?4:0;g=200<=a&&300>a||304===a;if(c){var u=n;for(var x=E,F,A,B,C,K=u.contents,W=u.dataTypes;"*"===W[0];)W.shift(),void 0===F&&(F=u.mimeType||x.getResponseHeader("Content-Type"));if(F)for(A in K)if(K[A]&&K[A].test(F)){W.unshift(A);break}if(W[0]in c)B=W[0];else{for(A in c){if(!W[0]||u.converters[A+" "+W[0]]){B=A;break}C||(C=A)}B=B||C}B?(B!==W[0]&&W.unshift(B),u=c[B]):u=void 0}a:{c=n;F=u;A=
E;B=g;var I;x={};K=c.dataTypes.slice();if(K[1])for(G in c.converters)x[G.toLowerCase()]=c.converters[G];for(C=K.shift();C;){c.responseFields[C]&&(A[c.responseFields[C]]=F);!V&&B&&c.dataFilter&&(F=c.dataFilter(F,c.dataType));var V=C;if(C=K.shift())if("*"===C)C=V;else if("*"!==V&&V!==C){var G=x[V+" "+C]||x["* "+C];if(!G)for(I in x)if(u=I.split(" "),u[1]===C&&(G=x[V+" "+u[0]]||x["* "+u[0]])){!0===G?G=x[I]:!0!==x[I]&&(C=u[0],K.unshift(u[1]));break}if(!0!==G)if(G&&c.throws)F=G(F);else try{F=G(F)}catch(gc){u=
{state:"parsererror",error:G?gc:"No conversion from "+V+" to "+C};break a}}}u={state:"success",data:F}}if(g)if(n.ifModified&&((l=E.getResponseHeader("Last-Modified"))&&(d.lastModified[z]=l),(l=E.getResponseHeader("etag"))&&(d.etag[z]=l)),204===a||"HEAD"===n.type)l="nocontent";else if(304===a)l="notmodified";else{l=u.state;var P=u.data;var H=u.error;g=!H}else if(H=l,a||!l)l="error",0>a&&(a=0);E.status=a;E.statusText=(b||l)+"";g?r.resolveWith(p,[P,l,E]):r.rejectWith(p,[E,l,H]);E.statusCode(v);v=void 0;
k&&q.trigger(g?"ajaxSuccess":"ajaxError",[E,n,g?P:H]);t.fireWith(p,[E,l]);k&&(q.trigger("ajaxComplete",[E,n]),--d.active||d.event.trigger("ajaxStop"))}}"object"===typeof a&&(b=a,a=void 0);b=b||{};var e,f,g,h,k,l,n=d.ajaxSetup({},b),p=n.context||n,q=n.context&&(p.nodeType||p.jquery)?d(p):d.event,r=d.Deferred(),t=d.Callbacks("once memory"),v=n.statusCode||{},u={},F={},A="canceled",E={readyState:0,getResponseHeader:function(a){var b;if(y){if(!g)for(g={};b=Ec.exec(f);)g[b[1].toLowerCase()+" "]=(g[b[1].toLowerCase()+
" "]||[]).concat(b[2]);b=g[a.toLowerCase()+" "]}return null==b?null:b.join(", ")},getAllResponseHeaders:function(){return y?f:null},setRequestHeader:function(a,b){null==y&&(a=F[a.toLowerCase()]=F[a.toLowerCase()]||a,u[a]=b);return this},overrideMimeType:function(a){null==y&&(n.mimeType=a);return this},statusCode:function(a){var b;if(a)if(y)E.always(a[E.status]);else for(b in a)v[b]=[v[b],a[b]];return this},abort:function(a){a=a||A;e&&e.abort(a);c(0,a);return this}};r.promise(E);n.url=((a||n.url||
Ea.href)+"").replace(Gc,Ea.protocol+"//");n.type=b.method||b.type||n.method||n.type;n.dataTypes=(n.dataType||"*").toLowerCase().match(ba)||[""];if(null==n.crossDomain){a=x.createElement("a");try{a.href=n.url,a.href=a.href,n.crossDomain=fb.protocol+"//"+fb.host!==a.protocol+"//"+a.host}catch(W){n.crossDomain=!0}}n.data&&n.processData&&"string"!==typeof n.data&&(n.data=d.param(n.data,n.traditional));yb(Mb,n,b,E);if(y)return E;(k=d.event&&n.global)&&0===d.active++&&d.event.trigger("ajaxStart");n.type=
n.type.toUpperCase();n.hasContent=!Fc.test(n.type);var z=n.url.replace(Cc,"");n.hasContent?n.data&&n.processData&&0===(n.contentType||"").indexOf("application/x-www-form-urlencoded")&&(n.data=n.data.replace(Bc,"+")):(a=n.url.slice(z.length),n.data&&(n.processData||"string"===typeof n.data)&&(z+=(eb.test(z)?"&":"?")+n.data,delete n.data),!1===n.cache&&(z=z.replace(Dc,"$1"),a=(eb.test(z)?"&":"?")+"_="+Kb++ +a),n.url=z+a);n.ifModified&&(d.lastModified[z]&&E.setRequestHeader("If-Modified-Since",d.lastModified[z]),
d.etag[z]&&E.setRequestHeader("If-None-Match",d.etag[z]));(n.data&&n.hasContent&&!1!==n.contentType||b.contentType)&&E.setRequestHeader("Content-Type",n.contentType);E.setRequestHeader("Accept",n.dataTypes[0]&&n.accepts[n.dataTypes[0]]?n.accepts[n.dataTypes[0]]+("*"!==n.dataTypes[0]?", "+Nb+"; q=0.01":""):n.accepts["*"]);for(l in n.headers)E.setRequestHeader(l,n.headers[l]);if(n.beforeSend&&(!1===n.beforeSend.call(p,E,n)||y))return E.abort();A="abort";t.add(n.complete);E.done(n.success);E.fail(n.error);
if(e=yb(ab,n,b,E)){E.readyState=1;k&&q.trigger("ajaxSend",[E,n]);if(y)return E;n.async&&0<n.timeout&&(h=m.setTimeout(function(){E.abort("timeout")},n.timeout));try{var y=!1;e.send(u,c)}catch(W){if(y)throw W;c(-1,W)}}else c(-1,"No Transport");return E},getJSON:function(a,b,c){return d.get(a,b,c,"json")},getScript:function(a,b){return d.get(a,void 0,b,"script")}});d.each(["get","post"],function(a,b){d[b]=function(a,e,f,g){t(e)&&(g=g||f,f=e,e=void 0);return d.ajax(d.extend({url:a,type:b,dataType:g,data:e,
success:f},d.isPlainObject(a)&&a))}});d._evalUrl=function(a,b){return d.ajax({url:a,type:"GET",dataType:"script",cache:!0,async:!1,global:!1,converters:{"text script":function(){}},dataFilter:function(a){d.globalEval(a,b)}})};d.fn.extend({wrapAll:function(a){this[0]&&(t(a)&&(a=a.call(this[0])),a=d(a,this[0].ownerDocument).eq(0).clone(!0),this[0].parentNode&&a.insertBefore(this[0]),a.map(function(){for(var a=this;a.firstElementChild;)a=a.firstElementChild;return a}).append(this));return this},wrapInner:function(a){return t(a)?
this.each(function(b){d(this).wrapInner(a.call(this,b))}):this.each(function(){var b=d(this),c=b.contents();c.length?c.wrapAll(a):b.append(a)})},wrap:function(a){var b=t(a);return this.each(function(c){d(this).wrapAll(b?a.call(this,c):a)})},unwrap:function(a){this.parent(a).not("body").each(function(){d(this).replaceWith(this.childNodes)});return this}});d.expr.pseudos.hidden=function(a){return!d.expr.pseudos.visible(a)};d.expr.pseudos.visible=function(a){return!!(a.offsetWidth||a.offsetHeight||a.getClientRects().length)};
d.ajaxSettings.xhr=function(){try{return new m.XMLHttpRequest}catch(a){}};var Hc={0:200,1223:204},Ha=d.ajaxSettings.xhr();z.cors=!!Ha&&"withCredentials"in Ha;z.ajax=Ha=!!Ha;d.ajaxTransport(function(a){var b,c;if(z.cors||Ha&&!a.crossDomain)return{send:function(d,f){var e,h=a.xhr();h.open(a.type,a.url,a.async,a.username,a.password);if(a.xhrFields)for(e in a.xhrFields)h[e]=a.xhrFields[e];a.mimeType&&h.overrideMimeType&&h.overrideMimeType(a.mimeType);a.crossDomain||d["X-Requested-With"]||(d["X-Requested-With"]=
"XMLHttpRequest");for(e in d)h.setRequestHeader(e,d[e]);b=function(a){return function(){b&&(b=c=h.onload=h.onerror=h.onabort=h.ontimeout=h.onreadystatechange=null,"abort"===a?h.abort():"error"===a?"number"!==typeof h.status?f(0,"error"):f(h.status,h.statusText):f(Hc[h.status]||h.status,h.statusText,"text"!==(h.responseType||"text")||"string"!==typeof h.responseText?{binary:h.response}:{text:h.responseText},h.getAllResponseHeaders()))}};h.onload=b();c=h.onerror=h.ontimeout=b("error");void 0!==h.onabort?
h.onabort=c:h.onreadystatechange=function(){4===h.readyState&&m.setTimeout(function(){b&&c()})};b=b("abort");try{h.send(a.hasContent&&a.data||null)}catch(k){if(b)throw k;}},abort:function(){b&&b()}}});d.ajaxPrefilter(function(a){a.crossDomain&&(a.contents.script=!1)});d.ajaxSetup({accepts:{script:"text/javascript, application/javascript, application/ecmascript, application/x-ecmascript"},contents:{script:/\b(?:java|ecma)script\b/},converters:{"text script":function(a){d.globalEval(a);return a}}});
d.ajaxPrefilter("script",function(a){void 0===a.cache&&(a.cache=!1);a.crossDomain&&(a.type="GET")});d.ajaxTransport("script",function(a){if(a.crossDomain||a.scriptAttrs){var b,c;return{send:function(e,f){b=d("<script>").attr(a.scriptAttrs||{}).prop({charset:a.scriptCharset,src:a.url}).on("load error",c=function(a){b.remove();c=null;a&&f("error"===a.type?404:200,a.type)});x.head.appendChild(b[0])},abort:function(){c&&c()}}}});var Ob=[],gb=/(=)\?(?=&|$)|\?\?/;d.ajaxSetup({jsonp:"callback",jsonpCallback:function(){var a=
Ob.pop()||d.expando+"_"+Kb++;this[a]=!0;return a}});d.ajaxPrefilter("json jsonp",function(a,b,c){var e,f=!1!==a.jsonp&&(gb.test(a.url)?"url":"string"===typeof a.data&&0===(a.contentType||"").indexOf("application/x-www-form-urlencoded")&&gb.test(a.data)&&"data");if(f||"jsonp"===a.dataTypes[0]){var g=a.jsonpCallback=t(a.jsonpCallback)?a.jsonpCallback():a.jsonpCallback;f?a[f]=a[f].replace(gb,"$1"+g):!1!==a.jsonp&&(a.url+=(eb.test(a.url)?"&":"?")+a.jsonp+"="+g);a.converters["script json"]=function(){e||
d.error(g+" was not called");return e[0]};a.dataTypes[0]="json";var h=m[g];m[g]=function(){e=arguments};c.always(function(){void 0===h?d(m).removeProp(g):m[g]=h;a[g]&&(a.jsonpCallback=b.jsonpCallback,Ob.push(g));e&&t(h)&&h(e[0]);e=h=void 0});return"script"}});z.createHTMLDocument=function(){var a=x.implementation.createHTMLDocument("").body;a.innerHTML="<form></form><form></form>";return 2===a.childNodes.length}();d.parseHTML=function(a,b,c){if("string"!==typeof a)return[];"boolean"===typeof b&&(c=
b,b=!1);if(!b)if(z.createHTMLDocument){b=x.implementation.createHTMLDocument("");var e=b.createElement("base");e.href=x.location.href;b.head.appendChild(e)}else b=x;e=Cb.exec(a);c=!c&&[];if(e)return[b.createElement(e[1])];e=Na([a],b,c);c&&c.length&&d(c).remove();return d.merge([],e.childNodes)};d.fn.load=function(a,b,c){var e,f,g=this,h=a.indexOf(" ");if(-1<h){var k=na(a.slice(h));a=a.slice(0,h)}t(b)?(c=b,b=void 0):b&&"object"===typeof b&&(e="POST");0<g.length&&d.ajax({url:a,type:e||"GET",dataType:"html",
data:b}).done(function(a){f=arguments;g.html(k?d("<div>").append(d.parseHTML(a)).find(k):a)}).always(c&&function(a,b){g.each(function(){c.apply(this,f||[a.responseText,b,a])})});return this};d.each("ajaxStart ajaxStop ajaxComplete ajaxError ajaxSuccess ajaxSend".split(" "),function(a,b){d.fn[b]=function(a){return this.on(b,a)}});d.expr.pseudos.animated=function(a){return d.grep(d.timers,function(b){return a===b.elem}).length};d.offset={setOffset:function(a,b,c){var e=d.css(a,"position"),f=d(a),g=
{};"static"===e&&(a.style.position="relative");var h=f.offset();var k=d.css(a,"top");var l=d.css(a,"left");("absolute"===e||"fixed"===e)&&-1<(k+l).indexOf("auto")?(l=f.position(),k=l.top,l=l.left):(k=parseFloat(k)||0,l=parseFloat(l)||0);t(b)&&(b=b.call(a,c,d.extend({},h)));null!=b.top&&(g.top=b.top-h.top+k);null!=b.left&&(g.left=b.left-h.left+l);"using"in b?b.using.call(a,g):f.css(g)}};d.fn.extend({offset:function(a){if(arguments.length)return void 0===a?this:this.each(function(b){d.offset.setOffset(this,
a,b)});var b;if(b=this[0]){if(!b.getClientRects().length)return{top:0,left:0};var c=b.getBoundingClientRect();b=b.ownerDocument.defaultView;return{top:c.top+b.pageYOffset,left:c.left+b.pageXOffset}}},position:function(){if(this[0]){var a,b=this[0],c={top:0,left:0};if("fixed"===d.css(b,"position"))var e=b.getBoundingClientRect();else{e=this.offset();var f=b.ownerDocument;for(a=b.offsetParent||f.documentElement;a&&(a===f.body||a===f.documentElement)&&"static"===d.css(a,"position");)a=a.parentNode;a&&
a!==b&&1===a.nodeType&&(c=d(a).offset(),c.top+=d.css(a,"borderTopWidth",!0),c.left+=d.css(a,"borderLeftWidth",!0))}return{top:e.top-c.top-d.css(b,"marginTop",!0),left:e.left-c.left-d.css(b,"marginLeft",!0)}}},offsetParent:function(){return this.map(function(){for(var a=this.offsetParent;a&&"static"===d.css(a,"position");)a=a.offsetParent;return a||ua})}});d.each({scrollLeft:"pageXOffset",scrollTop:"pageYOffset"},function(a,b){var c="pageYOffset"===b;d.fn[a]=function(d){return ia(this,function(a,d,
e){if(va(a))var f=a;else 9===a.nodeType&&(f=a.defaultView);if(void 0===e)return f?f[b]:a[d];f?f.scrollTo(c?f.pageXOffset:e,c?e:f.pageYOffset):a[d]=e},a,d,arguments.length)}});d.each(["top","left"],function(a,b){d.cssHooks[b]=pb(z.pixelPosition,function(a,e){if(e)return e=Ca(a,b),Va.test(e)?d(a).position()[b]+"px":e})});d.each({Height:"height",Width:"width"},function(a,b){d.each({padding:"inner"+a,content:b,"":"outer"+a},function(c,e){d.fn[e]=function(f,g){var h=arguments.length&&(c||"boolean"!==typeof f),
k=c||(!0===f||!0===g?"margin":"border");return ia(this,function(b,c,f){return va(b)?0===e.indexOf("outer")?b["inner"+a]:b.document.documentElement["client"+a]:9===b.nodeType?(c=b.documentElement,Math.max(b.body["scroll"+a],c["scroll"+a],b.body["offset"+a],c["offset"+a],c["client"+a])):void 0===f?d.css(b,c,k):d.style(b,c,f,k)},b,h?f:void 0,h)}})});d.each("blur focus focusin focusout resize scroll click dblclick mousedown mouseup mousemove mouseover mouseout mouseenter mouseleave change select submit keydown keypress keyup contextmenu".split(" "),
function(a,b){d.fn[b]=function(a,d){return 0<arguments.length?this.on(b,null,a,d):this.trigger(b)}});d.fn.extend({hover:function(a,b){return this.mouseenter(a).mouseleave(b||a)}});d.fn.extend({bind:function(a,b,c){return this.on(a,null,b,c)},unbind:function(a,b){return this.off(a,null,b)},delegate:function(a,b,c,d){return this.on(b,a,c,d)},undelegate:function(a,b,c){return 1===arguments.length?this.off(a,"**"):this.off(b,a||"**",c)}});d.proxy=function(a,b){if("string"===typeof b){var c=a[b];b=a;a=
c}if(t(a)){var e=ja.call(arguments,2);c=function(){return a.apply(b||this,e.concat(ja.call(arguments)))};c.guid=a.guid=a.guid||d.guid++;return c}};d.holdReady=function(a){a?d.readyWait++:d.ready(!0)};d.isArray=Array.isArray;d.parseJSON=JSON.parse;d.nodeName=M;d.isFunction=t;d.isWindow=va;d.camelCase=u;d.type=H;d.now=Date.now;d.isNumeric=function(a){var b=d.type(a);return("number"===b||"string"===b)&&!isNaN(a-parseFloat(a))};"function"===typeof define&&define.amd&&define("jquery",[],function(){return d});
var Ic=m.jQuery,Jc=m.$;d.noConflict=function(a){m.$===d&&(m.$=Jc);a&&m.jQuery===d&&(m.jQuery=Ic);return d};I||(m.jQuery=m.$=d);return d});
window.yii=function(m){function I(){m.ajaxPrefilter(function(m,q,r){!m.crossDomain&&y.getCsrfParam()&&r.setRequestHeader("X-CSRF-Token",y.getCsrfToken())});y.refreshCsrfToken()}function O(){m(document).ajaxComplete(function(m,q){(m=q&&q.getResponseHeader("X-Redirect"))&&window.location.assign(m)})}function H(){var p={};m("script[src]").each(function(){var m=aa(this.src);p[m]=!0});m.ajaxPrefilter("script",function(m,r,y){if("jsonp"!=m.dataType){m=aa(m.url);r=!0===p[m]&&!M(m);var q=void 0!==p[m]&&!0===
p[m].xhrDone;if(r||q)y.abort();else{if(void 0===p[m]||!0===p[m])p[m]={xhrList:[],xhrDone:!1};y.done(function(m,q,r){if(!0!==p[r.yiiUrl].xhrDone){p[r.yiiUrl].xhrDone=!0;m=0;for(q=p[r.yiiUrl].xhrList.length;m<q;m++){var u=p[r.yiiUrl].xhrList[m];u&&u.readyState!==XMLHttpRequest.DONE&&u.abort()}p[r.yiiUrl]=!0}}).fail(function(m,q){if("abort"!==q){delete p[m.yiiUrl].xhrList[m.yiiIndex];q=!0;for(var r=0,u=p[m.yiiUrl].xhrList.length;r<u;r++)p[m.yiiUrl].xhrList[r]&&(q=!1);q&&delete p[m.yiiUrl]}});y.yiiIndex=
p[m].xhrList.length;y.yiiUrl=m;p[m].xhrList[y.yiiIndex]=y}}});m(document).ajaxComplete(function(){var p=[];m("link[rel=stylesheet]").each(function(){var q=aa(this.href);M(q)||(-1===m.inArray(q,p)?p.push(q):m(this).remove())})})}function R(){var p=function(p){var q=m(this),K=q.data("method"),A=q.data("confirm"),F=q.data("form");if(void 0===K&&void 0===A&&void 0===F)return!0;void 0!==A&&!1!==A&&""!==A?m.proxy(y.confirm,this)(A,function(){y.handleAction(q,p)}):y.handleAction(q,p);p.stopImmediatePropagation();
return!1};m(document).on("click.yii",y.clickableSelector,p).on("change.yii",y.changeableSelector,p)}function M(m){for(var p=0;p<y.reloadableScripts.length;p++){var r=aa(y.reloadableScripts[p]);if(!0===(new RegExp("^"+r.replace(/[\-\[\]\/\{\}\(\)\*\+\?\.\\\^\$\|]/g,"\\$&").split("\\*").join(".+")+"$")).test(m))return!0}return!1}function aa(m){return"/"===m.charAt(0)?y.getBaseCurrentUrl()+m:m}var y={reloadableScripts:[],clickableSelector:'a, button, input[type="submit"], input[type="button"], input[type="reset"], input[type="image"]',
changeableSelector:"select, input, textarea",getCsrfParam:function(){return m("meta[name=csrf-param]").attr("content")},getCsrfToken:function(){return m("meta[name=csrf-token]").attr("content")},setCsrfToken:function(p,q){m("meta[name=csrf-param]").attr("content",p);m("meta[name=csrf-token]").attr("content",q)},refreshCsrfToken:function(){var p=y.getCsrfToken();p&&m('form input[name="'+y.getCsrfParam()+'"]').val(p)},confirm:function(m,q,r){window.confirm(m)?!q||q():!r||r()},handleAction:function(p,
q){var r=p.attr("data-form")?m("#"+p.attr("data-form")):p.closest("form"),K=!p.data("method")&&r?r.attr("method"):p.data("method"),A=p.attr("href"),F=A&&"#"!==A,u=p.data("params"),I=u&&m.isPlainObject(u),H=p.data("pjax");H=void 0!==H&&0!==H&&m.support.pjax;var O={};m.each("submit reset elements length name acceptCharset action enctype method target".split(" "),function(m,p){I&&u.hasOwnProperty(p)&&console.error("Parameter name '"+p+"' conflicts with a same named form property. Please use another name.")});
if(H){var M=p.data("pjax-container");void 0!==M&&M.length||(M=p.closest("[data-pjax-container]").attr("id")?"#"+p.closest("[data-pjax-container]").attr("id"):"");M.length||(M="body");O={container:M,push:!!p.data("pjax-push-state"),replace:!!p.data("pjax-replace-state"),scrollTo:p.data("pjax-scrollto"),pushRedirect:p.data("pjax-push-redirect"),replaceRedirect:p.data("pjax-replace-redirect"),skipOuterContainers:p.data("pjax-skip-outer-containers"),timeout:p.data("pjax-timeout"),originalEvent:q,originalTarget:p}}if(void 0===
K)if(F)H?m.pjax.click(q,O):window.location.assign(A);else{if(p.is(":submit")&&r.length){if(H)r.on("submit",function(p){m.pjax.submit(p,O)});r.trigger("submit")}}else{var T=!r.length;if(T)F||(A=y.getCurrentUrl()),r=m("<form/>",{method:K,action:A}),(q=p.attr("target"))&&r.attr("target",q),/(get|post)/i.test(K)||(r.append(m("<input/>",{name:"_method",value:K,type:"hidden"})),K="post",r.attr("method",K)),/post/i.test(K)&&(K=y.getCsrfParam())&&r.append(m("<input/>",{name:K,value:y.getCsrfToken(),type:"hidden"})),
r.hide().appendTo("body");else{var R=r.attr("method");r.attr("method",K);if(F){var aa=r.attr("action");r.attr("action",A)}}if(K=r.data("yiiActiveForm"))K.submitObject=p;I&&m.each(u,function(p,q){r.append(m("<input/>").attr({name:p,value:q,type:"hidden"}))});if(H)r.on("submit",function(p){m.pjax.submit(p,O)});r.trigger("submit");m.when(r.data("yiiSubmitFinalizePromise")).done(function(){T?r.remove():(void 0!==aa&&r.attr("action",aa),r.attr("method",R),I&&m.each(u,function(p){m('input[name="'+p+'"]',
r).remove()}))})}},getQueryParams:function(p){var q=p.indexOf("?");if(0>q)return{};p=m.grep(p.substring(q+1).split("#")[0].split("&"),function(m){return""!==m});q={};for(var r=0,y=p.length;r<y;r++){var A=p[r].split("="),F=decodeURIComponent(A[0].replace(/\+/g,"%20"));A=decodeURIComponent(A[1].replace(/\+/g,"%20"));F.length&&(void 0===q[F]?q[F]=A||"":(m.isArray(q[F])||(q[F]=[q[F]]),q[F].push(A||"")))}return q},initModule:function(p){if(void 0===p.isActive||p.isActive)m.isFunction(p.init)&&p.init(),
m.each(p,function(){m.isPlainObject(this)&&y.initModule(this)})},init:function(){I();O();H();R()},getBaseCurrentUrl:function(){return window.location.protocol+"//"+window.location.host},getCurrentUrl:function(){return window.location.href}};return y}(window.jQuery);window.jQuery(function(){window.yii.initModule(window.yii)});
